// Tự động sinh từ dữ liệu vn.json
export const PROVINCE_OPTIONS = [
  {
    "value": "Thành phố Hà Nội",
    "label": "Thành phố Hà Nội"
  },
  {
    "value": "Tỉnh Cao Bằng",
    "label": "Tỉnh Cao Bằng"
  },
  {
    "value": "Tỉnh Tuyên Quang",
    "label": "Tỉnh Tuyên Quang"
  },
  {
    "value": "Tỉnh Điện Biên",
    "label": "Tỉnh Điện Biên"
  },
  {
    "value": "Tỉnh Lai Châu",
    "label": "Tỉnh Lai Châu"
  },
  {
    "value": "Tỉnh Sơn La",
    "label": "Tỉnh Sơn La"
  },
  {
    "value": "Tỉnh Lào Cai",
    "label": "Tỉnh Lào Cai"
  },
  {
    "value": "Tỉnh Thái Nguyên",
    "label": "Tỉnh Thái Nguyên"
  },
  {
    "value": "Tỉnh Lạng Sơn",
    "label": "Tỉnh Lạng Sơn"
  },
  {
    "value": "Tỉnh Quảng Ninh",
    "label": "Tỉnh Quảng Ninh"
  },
  {
    "value": "Tỉnh Bắc Ninh",
    "label": "Tỉnh Bắc Ninh"
  },
  {
    "value": "Tỉnh Phú Thọ",
    "label": "Tỉnh Phú Thọ"
  },
  {
    "value": "Thành phố Hải Phòng",
    "label": "Thành phố Hải Phòng"
  },
  {
    "value": "Tỉnh Hưng Yên",
    "label": "Tỉnh Hưng Yên"
  },
  {
    "value": "Tỉnh Ninh Bình",
    "label": "Tỉnh Ninh Bình"
  },
  {
    "value": "Tỉnh Thanh Hóa",
    "label": "Tỉnh Thanh Hóa"
  },
  {
    "value": "Tỉnh Nghệ An",
    "label": "Tỉnh Nghệ An"
  },
  {
    "value": "Tỉnh Hà Tĩnh",
    "label": "Tỉnh Hà Tĩnh"
  },
  {
    "value": "Tỉnh Quảng Trị",
    "label": "Tỉnh Quảng Trị"
  },
  {
    "value": "Thành phố Huế",
    "label": "Thành phố Huế"
  },
  {
    "value": "Thành phố Đà Nẵng",
    "label": "Thành phố Đà Nẵng"
  },
  {
    "value": "Tỉnh Quảng Ngãi",
    "label": "Tỉnh Quảng Ngãi"
  },
  {
    "value": "Tỉnh Gia Lai",
    "label": "Tỉnh Gia Lai"
  },
  {
    "value": "Tỉnh Khánh Hòa",
    "label": "Tỉnh Khánh Hòa"
  },
  {
    "value": "Tỉnh Đắk Lắk",
    "label": "Tỉnh Đắk Lắk"
  },
  {
    "value": "Tỉnh Lâm Đồng",
    "label": "Tỉnh Lâm Đồng"
  },
  {
    "value": "Tỉnh Đồng Nai",
    "label": "Tỉnh Đồng Nai"
  },
  {
    "value": "Thành phố Hồ Chí Minh",
    "label": "Thành phố Hồ Chí Minh"
  },
  {
    "value": "Tỉnh Tây Ninh",
    "label": "Tỉnh Tây Ninh"
  },
  {
    "value": "Tỉnh Đồng Tháp",
    "label": "Tỉnh Đồng Tháp"
  },
  {
    "value": "Tỉnh Vĩnh Long",
    "label": "Tỉnh Vĩnh Long"
  },
  {
    "value": "Tỉnh An Giang",
    "label": "Tỉnh An Giang"
  },
  {
    "value": "Thành phố Cần Thơ",
    "label": "Thành phố Cần Thơ"
  },
  {
    "value": "Tỉnh Cà Mau",
    "label": "Tỉnh Cà Mau"
  }
];

export const DISTRICT_WARD_MAP: Record<string, string[]> = {
  "Thành phố Hà Nội": [
    "Phường Ba Đình",
    "Phường Ngọc Hà",
    "Phường Giảng Võ",
    "Phường Hoàn Kiếm",
    "Phường Cửa Nam",
    "Phường Phú Thượng",
    "Phường Hồng Hà",
    "Phường Tây Hồ",
    "Phường Bồ Đề",
    "Phường Việt Hưng",
    "Phường Phúc Lợi",
    "Phường Long Biên",
    "Phường Nghĩa Đô",
    "Phường Cầu Giấy",
    "Phường Yên Hòa",
    "Phường Ô Chợ Dừa",
    "Phường Láng",
    "Phường Văn Miếu - Quốc Tử Giám",
    "Phường Kim Liên",
    "Phường Đống Đa",
    "Phường Hai Bà Trưng",
    "Phường Vĩnh Tuy",
    "Phường Bạch Mai",
    "Phường Vĩnh Hưng",
    "Phường Định Công",
    "Phường Tương Mai",
    "Phường Lĩnh Nam",
    "Phường Hoàng Mai",
    "Phường Hoàng Liệt",
    "Phường Yên Sở",
    "Phường Phương Liệt",
    "Phường Khương Đình",
    "Phường Thanh Xuân",
    "Phường Từ Liêm",
    "Phường Thượng Cát",
    "Phường Đông Ngạc",
    "Phường Xuân Đỉnh",
    "Phường Tây Tựu",
    "Phường Phú Diễn",
    "Phường Xuân Phương",
    "Phường Tây Mỗ",
    "Phường Đại Mỗ",
    "Phường Thanh Liệt",
    "Phường Kiến Hưng",
    "Phường Hà Đông",
    "Phường Yên Nghĩa",
    "Phường Phú Lương",
    "Phường Sơn Tây",
    "Phường Tùng Thiện",
    "Phường Dương Nội",
    "Phường Chương Mỹ",
    "Xã Sóc Sơn",
    "Xã Kim Anh",
    "Xã Trung Giã",
    "Xã Đa Phúc",
    "Xã Nội Bài",
    "Xã Đông Anh",
    "Xã Phúc Thịnh",
    "Xã Thư Lâm",
    "Xã Thiên Lộc",
    "Xã Vĩnh Thanh",
    "Xã Phù Đổng",
    "Xã Thuận An",
    "Xã Gia Lâm",
    "Xã Bát Tràng",
    "Xã Thanh Trì",
    "Xã Đại Thanh",
    "Xã Ngọc Hồi",
    "Xã Nam Phù",
    "Xã Yên Xuân",
    "Xã Quang Minh",
    "Xã Yên Lãng",
    "Xã Tiến Thắng",
    "Xã Mê Linh",
    "Xã Đoài Phương",
    "Xã Quảng Oai",
    "Xã Cổ Đô",
    "Xã Minh Châu",
    "Xã Vật Lại",
    "Xã Bất Bạt",
    "Xã Suối Hai",
    "Xã Ba Vì",
    "Xã Yên Bài",
    "Xã Phúc Thọ",
    "Xã Phúc Lộc",
    "Xã Hát Môn",
    "Xã Đan Phượng",
    "Xã Liên Minh",
    "Xã Ô Diên",
    "Xã Hoài Đức",
    "Xã Dương Hòa",
    "Xã Sơn Đồng",
    "Xã An Khánh",
    "Xã Quốc Oai",
    "Xã Kiều Phú",
    "Xã Hưng Đạo",
    "Xã Phú Cát",
    "Xã Thạch Thất",
    "Xã Hạ Bằng",
    "Xã Hòa Lạc",
    "Xã Tây Phương",
    "Xã Phú Nghĩa",
    "Xã Xuân Mai",
    "Xã Quảng Bị",
    "Xã Trần Phú",
    "Xã Hòa Phú",
    "Xã Thanh Oai",
    "Xã Bình Minh",
    "Xã Tam Hưng",
    "Xã Dân Hòa",
    "Xã Thường Tín",
    "Xã Hồng Vân",
    "Xã Thượng Phúc",
    "Xã Chương Dương",
    "Xã Phú Xuyên",
    "Xã Phượng Dực",
    "Xã Chuyên Mỹ",
    "Xã Đại Xuyên",
    "Xã Vân Đình",
    "Xã Ứng Thiên",
    "Xã Ứng Hòa",
    "Xã Hòa Xá",
    "Xã Mỹ Đức",
    "Xã Phúc Sơn",
    "Xã Hồng Sơn",
    "Xã Hương Sơn"
  ],
  "Tỉnh Cao Bằng": [
    "Phường Thục Phán",
    "Phường Nùng Trí Cao",
    "Phường Tân Giang",
    "Xã Bảo Lâm",
    "Xã Lý Bôn",
    "Xã Nam Quang",
    "Xã Quảng Lâm",
    "Xã Yên Thổ",
    "Xã Bảo Lạc",
    "Xã Cốc Pàng",
    "Xã Cô Ba",
    "Xã Khánh Xuân",
    "Xã Xuân Trường",
    "Xã Hưng Đạo",
    "Xã Huy Giáp",
    "Xã Sơn Lộ",
    "Xã Thông Nông",
    "Xã Cần Yên",
    "Xã Thanh Long",
    "Xã Trường Hà",
    "Xã Lũng Nặm",
    "Xã Tổng Cọt",
    "Xã Hà Quảng",
    "Xã Trà Lĩnh",
    "Xã Quang Hán",
    "Xã Quang Trung",
    "Xã Trùng Khánh",
    "Xã Đình Phong",
    "Xã Đàm Thủy",
    "Xã Đoài Dương",
    "Xã Lý Quốc",
    "Xã Quang Long",
    "Xã Hạ Lang",
    "Xã Vinh Quý",
    "Xã Quảng Uyên",
    "Xã Độc Lập",
    "Xã Hạnh Phúc",
    "Xã Bế Văn Đàn",
    "Xã Phục Hòa",
    "Xã Hòa An",
    "Xã Nam Tuấn",
    "Xã Nguyễn Huệ",
    "Xã Bạch Đằng",
    "Xã Nguyên Bình",
    "Xã Tĩnh Túc",
    "Xã Ca Thành",
    "Xã Minh Tâm",
    "Xã Phan Thanh",
    "Xã Tam Kim",
    "Xã Thành Công",
    "Xã Đông Khê",
    "Xã Canh Tân",
    "Xã Kim Đồng",
    "Xã Minh Khai",
    "Xã Thạch An",
    "Xã Đức Long"
  ],
  "Tỉnh Tuyên Quang": [
    "Phường Hà Giang 2",
    "Phường Hà Giang 1",
    "Phường Nông Tiến",
    "Phường Minh Xuân",
    "Phường Mỹ Lâm",
    "Phường An Tường",
    "Phường Bình Thuận",
    "Xã Ngọc Đường",
    "Xã Phú Linh",
    "Xã Lũng Cú",
    "Xã Đồng Văn",
    "Xã Sà Phìn",
    "Xã Phó Bảng",
    "Xã Lũng Phìn",
    "Xã Mèo Vạc",
    "Xã Sơn Vĩ",
    "Xã Sủng Máng",
    "Xã Khâu Vai",
    "Xã Tát Ngà",
    "Xã Niêm Sơn",
    "Xã Yên Minh",
    "Xã Thắng Mố",
    "Xã Bạch Đích",
    "Xã Mậu Duệ",
    "Xã Ngọc Long",
    "Xã Đường Thượng",
    "Xã Du Già",
    "Xã Quản Bạ",
    "Xã Cán Tỷ",
    "Xã Nghĩa Thuận",
    "Xã Tùng Vài",
    "Xã Lùng Tám",
    "Xã Vị Xuyên",
    "Xã Minh Tân",
    "Xã Thuận Hòa",
    "Xã Tùng Bá",
    "Xã Thanh Thủy",
    "Xã Lao Chải",
    "Xã Cao Bồ",
    "Xã Thượng Sơn",
    "Xã Việt Lâm",
    "Xã Linh Hồ",
    "Xã Bạch Ngọc",
    "Xã Minh Sơn",
    "Xã Giáp Trung",
    "Xã Bắc Mê",
    "Xã Minh Ngọc",
    "Xã Yên Cường",
    "Xã Đường Hồng",
    "Xã Hoàng Su Phì",
    "Xã Bản Máy",
    "Xã Thàng Tín",
    "Xã Tân Tiến",
    "Xã Pờ Ly Ngài",
    "Xã Nậm Dịch",
    "Xã Hồ Thầu",
    "Xã Thông Nguyên",
    "Xã Pà Vầy Sủ",
    "Xã Xín Mần",
    "Xã Trung Thịnh",
    "Xã Nấm Dẩn",
    "Xã Quảng Nguyên",
    "Xã Khuôn Lùng",
    "Xã Bắc Quang",
    "Xã Vĩnh Tuy",
    "Xã Đồng Tâm",
    "Xã Tân Quang",
    "Xã Bằng Hành",
    "Xã Liên Hiệp",
    "Xã Hùng An",
    "Xã Đồng Yên",
    "Xã Tiên Nguyên",
    "Xã Yên Thành",
    "Xã Quang Bình",
    "Xã Tân Trịnh",
    "Xã Bằng Lang",
    "Xã Xuân Giang",
    "Xã Tiên Yên",
    "Xã Nà Hang",
    "Xã Thượng Nông",
    "Xã Côn Lôn",
    "Xã Yên Hoa",
    "Xã Hồng Thái",
    "Xã Lâm Bình",
    "Xã Thượng Lâm",
    "Xã Chiêm Hóa",
    "Xã Bình An",
    "Xã Minh Quang",
    "Xã Trung Hà",
    "Xã Tân Mỹ",
    "Xã Yên Lập",
    "Xã Tân An",
    "Xã Kiên Đài",
    "Xã Kim Bình",
    "Xã Hòa An",
    "Xã Tri Phú",
    "Xã Yên Nguyên",
    "Xã Hàm Yên",
    "Xã Bạch Xa",
    "Xã Phù Lưu",
    "Xã Yên Phú",
    "Xã Bình Xa",
    "Xã Thái Sơn",
    "Xã Thái Hòa",
    "Xã Hùng Đức",
    "Xã Lực Hành",
    "Xã Kiến Thiết",
    "Xã Xuân Vân",
    "Xã Hùng Lợi",
    "Xã Trung Sơn",
    "Xã Tân Long",
    "Xã Yên Sơn",
    "Xã Thái Bình",
    "Xã Nhữ Khê",
    "Xã Sơn Dương",
    "Xã Tân Trào",
    "Xã Bình Ca",
    "Xã Minh Thanh",
    "Xã Đông Thọ",
    "Xã Tân Thanh",
    "Xã Hồng Sơn",
    "Xã Phú Lương",
    "Xã Sơn Thủy",
    "Xã Trường Sinh"
  ],
  "Tỉnh Điện Biên": [
    "Phường Điện Biên Phủ",
    "Phường Mường Lay",
    "Phường Mường Thanh",
    "Xã Sín Thầu",
    "Xã Mường Nhé",
    "Xã Nậm Kè",
    "Xã Mường Toong",
    "Xã Quảng Lâm",
    "Xã Mường Chà",
    "Xã Nà Hỳ",
    "Xã Na Sang",
    "Xã Chà Tở",
    "Xã Nà Bủng",
    "Xã Mường Tùng",
    "Xã Pa Ham",
    "Xã Nậm Nèn",
    "Xã Si Pa Phìn",
    "Xã Mường Pồn",
    "Xã Na Son",
    "Xã Xa Dung",
    "Xã Mường Luân",
    "Xã Tủa Chùa",
    "Xã Tủa Thàng",
    "Xã Sín Chải",
    "Xã Sính Phình",
    "Xã Sáng Nhè",
    "Xã Tuần Giáo",
    "Xã Mường Ảng",
    "Xã Pú Nhung",
    "Xã Mường Mùn",
    "Xã Chiềng Sinh",
    "Xã Quài Tở",
    "Xã Búng Lao",
    "Xã Mường Lạn",
    "Xã Nà Tấu",
    "Xã Mường Phăng",
    "Xã Thanh Nưa",
    "Xã Thanh Yên",
    "Xã Thanh An",
    "Xã Sam Mứn",
    "Xã Núa Ngam",
    "Xã Mường Nhà",
    "Xã Pu Nhi",
    "Xã Phình Giàng",
    "Xã Tìa Dình"
  ],
  "Tỉnh Lai Châu": [
    "Phường Đoàn Kết",
    "Phường Tân Phong",
    "Xã Bình Lư",
    "Xã Sin Suối Hồ",
    "Xã Tả Lèng",
    "Xã Bản Bo",
    "Xã Khun Há",
    "Xã Bum Tở",
    "Xã Nậm Hàng",
    "Xã Thu Lũm",
    "Xã Pa Ủ",
    "Xã Mường Tè",
    "Xã Mù Cả",
    "Xã Hua Bum",
    "Xã Tà Tổng",
    "Xã Bum Nưa",
    "Xã Mường Mô",
    "Xã Sìn Hồ",
    "Xã Lê Lợi",
    "Xã Pa Tần",
    "Xã Hồng Thu",
    "Xã Nậm Tăm",
    "Xã Tủa Sín Chải",
    "Xã Pu Sam Cáp",
    "Xã Nậm Mạ",
    "Xã Nậm Cuổi",
    "Xã Phong Thổ",
    "Xã Sì Lở Lầu",
    "Xã Dào San",
    "Xã Khổng Lào",
    "Xã Than Uyên",
    "Xã Tân Uyên",
    "Xã Mường Khoa",
    "Xã Nậm Sỏ",
    "Xã Pắc Ta",
    "Xã Mường Than",
    "Xã Mường Kim",
    "Xã Khoen On"
  ],
  "Tỉnh Sơn La": [
    "Phường Tô Hiệu",
    "Phường Chiềng An",
    "Phường Chiềng Cơi",
    "Phường Chiềng Sinh",
    "Phường Mộc Sơn",
    "Phường Mộc Châu",
    "Phường Thảo Nguyên",
    "Phường Vân Sơn",
    "Xã Mường Chiên",
    "Xã Mường Giôn",
    "Xã Quỳnh Nhai",
    "Xã Mường Sại",
    "Xã Thuận Châu",
    "Xã Bình Thuận",
    "Xã Mường É",
    "Xã Chiềng La",
    "Xã Mường Khiêng",
    "Xã Mường Bám",
    "Xã Long Hẹ",
    "Xã Co Mạ",
    "Xã Nậm Lầu",
    "Xã Muổi Nọi",
    "Xã Mường La",
    "Xã Chiềng Lao",
    "Xã Ngọc Chiến",
    "Xã Mường Bú",
    "Xã Chiềng Hoa",
    "Xã Bắc Yên",
    "Xã Xím Vàng",
    "Xã Tà Xùa",
    "Xã Pắc Ngà",
    "Xã Tạ Khoa",
    "Xã Chiềng Sại",
    "Xã Suối Tọ",
    "Xã Mường Cơi",
    "Xã Phù Yên",
    "Xã Gia Phù",
    "Xã Mường Bang",
    "Xã Tường Hạ",
    "Xã Kim Bon",
    "Xã Tân Phong",
    "Xã Chiềng Sơn",
    "Xã Tân Yên",
    "Xã Đoàn Kết",
    "Xã Song Khủa",
    "Xã Tô Múa",
    "Xã Lóng Sập",
    "Xã Vân Hồ",
    "Xã Xuân Nha",
    "Xã Yên Châu",
    "Xã Chiềng Hặc",
    "Xã Yên Sơn",
    "Xã Lóng Phiêng",
    "Xã Phiêng Khoài",
    "Xã Mai Sơn",
    "Xã Chiềng Sung",
    "Xã Mường Chanh",
    "Xã Chiềng Mung",
    "Xã Chiềng Mai",
    "Xã Tà Hộc",
    "Xã Phiêng Cằm",
    "Xã Phiêng Pằn",
    "Xã Sông Mã",
    "Xã Bó Sinh",
    "Xã Mường Lầm",
    "Xã Nậm Ty",
    "Xã Chiềng Sơ",
    "Xã Chiềng Khoong",
    "Xã Huổi Một",
    "Xã Mường Hung",
    "Xã Chiềng Khương",
    "Xã Púng Bánh",
    "Xã Sốp Cộp",
    "Xã Mường Lèo",
    "Xã Mường Lạn"
  ],
  "Tỉnh Lào Cai": [
    "Phường Lào Cai",
    "Phường Cam Đường",
    "Phường Sa Pa",
    "Phường Yên Bái",
    "Phường Nam Cường",
    "Phường Văn Phú",
    "Phường Nghĩa Lộ",
    "Phường Âu Lâu",
    "Phường Trung Tâm",
    "Phường Cầu Thia",
    "Xã Hợp Thành",
    "Xã Bát Xát",
    "Xã A Mú Sung",
    "Xã Trịnh Tường",
    "Xã Y Tý",
    "Xã Dền Sáng",
    "Xã Bản Xèo",
    "Xã Mường Hum",
    "Xã Cốc San",
    "Xã Pha Long",
    "Xã Mường Khương",
    "Xã Cao Sơn",
    "Xã Bản Lầu",
    "Xã Si Ma Cai",
    "Xã Sín Chéng",
    "Xã Bắc Hà",
    "Xã Tả Củ Tỷ",
    "Xã Lùng Phình",
    "Xã Bản Liền",
    "Xã Bảo Nhai",
    "Xã Cốc Lầu",
    "Xã Phong Hải",
    "Xã Bảo Thắng",
    "Xã Tằng Loỏng",
    "Xã Gia Phú",
    "Xã Xuân Quang",
    "Xã Bảo Yên",
    "Xã Nghĩa Đô",
    "Xã Xuân Hòa",
    "Xã Thượng Hà",
    "Xã Bảo Hà",
    "Xã Phúc Khánh",
    "Xã Ngũ Chỉ Sơn",
    "Xã Tả Phìn",
    "Xã Tả Van",
    "Xã Mường Bo",
    "Xã Bản Hồ",
    "Xã Võ Lao",
    "Xã Nậm Chày",
    "Xã Văn Bàn",
    "Xã Nậm Xé",
    "Xã Chiềng Ken",
    "Xã Khánh Yên",
    "Xã Dương Quỳ",
    "Xã Minh Lương",
    "Xã Lục Yên",
    "Xã Lâm Thượng",
    "Xã Tân Lĩnh",
    "Xã Khánh Hòa",
    "Xã Mường Lai",
    "Xã Phúc Lợi",
    "Xã Mậu A",
    "Xã Lâm Giang",
    "Xã Châu Quế",
    "Xã Đông Cuông",
    "Xã Phong Dụ Hạ",
    "Xã Phong Dụ Thượng",
    "Xã Tân Hợp",
    "Xã Xuân Ái",
    "Xã Mỏ Vàng",
    "Xã Mù Cang Chải",
    "Xã Nậm Có",
    "Xã Khao Mang",
    "Xã Lao Chải",
    "Xã Chế Tạo",
    "Xã Púng Luông",
    "Xã Trấn Yên",
    "Xã Quy Mông",
    "Xã Lương Thịnh",
    "Xã Việt Hồng",
    "Xã Hưng Khánh",
    "Xã Hạnh Phúc",
    "Xã Tà Xi Láng",
    "Xã Trạm Tấu",
    "Xã Phình Hồ",
    "Xã Tú Lệ",
    "Xã Gia Hội",
    "Xã Sơn Lương",
    "Xã Liên Sơn",
    "Xã Văn Chấn",
    "Xã Cát Thịnh",
    "Xã Chấn Thịnh",
    "Xã Thượng Bằng La",
    "Xã Nghĩa Tâm",
    "Xã Yên Bình",
    "Xã Thác Bà",
    "Xã Cảm Nhân",
    "Xã Yên Thành",
    "Xã Bảo Ái"
  ],
  "Tỉnh Thái Nguyên": [
    "Phường Đức Xuân",
    "Phường Bắc Kạn",
    "Phường Phan Đình Phùng",
    "Phường Quyết Thắng",
    "Phường Gia Sàng",
    "Phường Quan Triều",
    "Phường Tích Lương",
    "Phường Sông Công",
    "Phường Bách Quang",
    "Phường Bá Xuyên",
    "Phường Linh Sơn",
    "Phường Phúc Thuận",
    "Phường Phổ Yên",
    "Phường Vạn Xuân",
    "Phường Trung Thành",
    "Xã Phong Quang",
    "Xã Bằng Thành",
    "Xã Cao Minh",
    "Xã Nghiên Loan",
    "Xã Phúc Lộc",
    "Xã Ba Bể",
    "Xã Chợ Rã",
    "Xã Thượng Minh",
    "Xã Đồng Phúc",
    "Xã Nà Phặc",
    "Xã Bằng Vân",
    "Xã Ngân Sơn",
    "Xã Thượng Quan",
    "Xã Hiệp Lực",
    "Xã Phủ Thông",
    "Xã Vĩnh Thông",
    "Xã Cẩm Giàng",
    "Xã Bạch Thông",
    "Xã Chợ Đồn",
    "Xã Nam Cường",
    "Xã Quảng Bạch",
    "Xã Yên Thịnh",
    "Xã Nghĩa Tá",
    "Xã Yên Phong",
    "Xã Chợ Mới",
    "Xã Thanh Mai",
    "Xã Tân Kỳ",
    "Xã Thanh Thịnh",
    "Xã Yên Bình",
    "Xã Văn Lang",
    "Xã Cường Lợi",
    "Xã Na Rì",
    "Xã Trần Phú",
    "Xã Côn Minh",
    "Xã Xuân Dương",
    "Xã Đại Phúc",
    "Xã Tân Cương",
    "Xã Lam Vỹ",
    "Xã Kim Phượng",
    "Xã Phượng Tiến",
    "Xã Định Hóa",
    "Xã Trung Hội",
    "Xã Bình Yên",
    "Xã Phú Đình",
    "Xã Bình Thành",
    "Xã Phú Lương",
    "Xã Yên Trạch",
    "Xã Hợp Thành",
    "Xã Vô Tranh",
    "Xã Trại Cau",
    "Xã Văn Lăng",
    "Xã Quang Sơn",
    "Xã Văn Hán",
    "Xã Đồng Hỷ",
    "Xã Nam Hòa",
    "Xã Võ Nhai",
    "Xã Sảng Mộc",
    "Xã Nghinh Tường",
    "Xã Thần Sa",
    "Xã La Hiên",
    "Xã Tràng Xá",
    "Xã Dân Tiến",
    "Xã Phú Xuyên",
    "Xã Đức Lương",
    "Xã Phú Lạc",
    "Xã Phú Thịnh",
    "Xã An Khánh",
    "Xã La Bằng",
    "Xã Đại Từ",
    "Xã Vạn Phú",
    "Xã Quân Chu",
    "Xã Thành Công",
    "Xã Phú Bình",
    "Xã Tân Khánh",
    "Xã Tân Thành",
    "Xã Điềm Thụy",
    "Xã Kha Sơn"
  ],
  "Tỉnh Lạng Sơn": [
    "Phường Đông Kinh",
    "Phường Lương Văn Tri",
    "Phường Tam Thanh",
    "Phường Kỳ Lừa",
    "Xã Đoàn Kết",
    "Xã Quốc Khánh",
    "Xã Tân Tiến",
    "Xã Kháng Chiến",
    "Xã Thất Khê",
    "Xã Tràng Định",
    "Xã Quốc Việt",
    "Xã Hoa Thám",
    "Xã Quý Hòa",
    "Xã Hồng Phong",
    "Xã Thiện Hòa",
    "Xã Thiện Thuật",
    "Xã Thiện Long",
    "Xã Bình Gia",
    "Xã Tân Văn",
    "Xã Na Sầm",
    "Xã Thụy Hùng",
    "Xã Hội Hoan",
    "Xã Văn Lãng",
    "Xã Hoàng Văn Thụ",
    "Xã Đồng Đăng",
    "Xã Ba Sơn",
    "Xã Cao Lộc",
    "Xã Công Sơn",
    "Xã Văn Quan",
    "Xã Điềm He",
    "Xã Khánh Khê",
    "Xã Yên Phúc",
    "Xã Tri Lễ",
    "Xã Tân Đoàn",
    "Xã Bắc Sơn",
    "Xã Tân Tri",
    "Xã Hưng Vũ",
    "Xã Vũ Lễ",
    "Xã Vũ Lăng",
    "Xã Nhất Hòa",
    "Xã Hữu Lũng",
    "Xã Yên Bình",
    "Xã Hữu Liên",
    "Xã Vân Nham",
    "Xã Cai Kinh",
    "Xã Thiện Tân",
    "Xã Tân Thành",
    "Xã Tuấn Sơn",
    "Xã Chi Lăng",
    "Xã Bằng Mạc",
    "Xã Chiến Thắng",
    "Xã Nhân Lý",
    "Xã Vạn Linh",
    "Xã Quan Sơn",
    "Xã Na Dương",
    "Xã Lộc Bình",
    "Xã Mẫu Sơn",
    "Xã Khuất Xá",
    "Xã Thống Nhất",
    "Xã Lợi Bác",
    "Xã Xuân Dương",
    "Xã Đình Lập",
    "Xã Thái Bình",
    "Xã Kiên Mộc",
    "Xã Châu Sơn"
  ],
  "Tỉnh Quảng Ninh": [
    "Phường Hà Tu",
    "Phường Cao Xanh",
    "Phường Việt Hưng",
    "Phường Bãi Cháy",
    "Phường Hà Lầm",
    "Phường Hồng Gai",
    "Phường Hạ Long",
    "Phường Tuần Châu",
    "Phường Móng Cái 2",
    "Phường Móng Cái 1",
    "Phường Móng Cái 3",
    "Phường Mông Dương",
    "Phường Quang Hanh",
    "Phường Cửa Ông",
    "Phường Cẩm Phả",
    "Phường Uông Bí",
    "Phường Vàng Danh",
    "Phường Yên Tử",
    "Phường Hoành Bồ",
    "Phường Mạo Khê",
    "Phường Bình Khê",
    "Phường An Sinh",
    "Phường Đông Triều",
    "Phường Hoàng Quế",
    "Phường Quảng Yên",
    "Phường Đông Mai",
    "Phường Hiệp Hòa",
    "Phường Hà An",
    "Phường Liên Hòa",
    "Phường Phong Cốc",
    "Xã Hải Sơn",
    "Xã Hải Ninh",
    "Xã Vĩnh Thực",
    "Xã Hải Hòa",
    "Xã Bình Liêu",
    "Xã Hoành Mô",
    "Xã Lục Hồn",
    "Xã Tiên Yên",
    "Xã Điền Xá",
    "Xã Đông Ngũ",
    "Xã Hải Lạng",
    "Xã Đầm Hà",
    "Xã Quảng Tân",
    "Xã Quảng Hà",
    "Xã Quảng Đức",
    "Xã Đường Hoa",
    "Xã Cái Chiên",
    "Xã Ba Chẽ",
    "Xã Kỳ Thượng",
    "Xã Lương Minh",
    "Xã Quảng La",
    "Xã Thống Nhất",
    "Đặc khu Vân Đồn",
    "Đặc khu Cô Tô"
  ],
  "Tỉnh Bắc Ninh": [
    "Xã Mỹ Thái",
    "Phường Bắc Giang",
    "Phường Đa Mai",
    "Phường Chũ",
    "Phường Phượng Sơn",
    "Phường Yên Dũng",
    "Phường Tân An",
    "Phường Tiền Phong",
    "Phường Tân Tiến",
    "Phường Cảnh Thụy",
    "Phường Tự Lạn",
    "Phường Việt Yên",
    "Phường Nếnh",
    "Phường Vân Hà",
    "Phường Vũ Ninh",
    "Phường Kinh Bắc",
    "Phường Võ Cường",
    "Phường Quế Võ",
    "Phường Nhân Hòa",
    "Phường Phương Liễu",
    "Phường Nam Sơn",
    "Phường Bồng Lai",
    "Phường Đào Viên",
    "Phường Hạp Lĩnh",
    "Phường Từ Sơn",
    "Phường Tam Sơn",
    "Phường Phù Khê",
    "Phường Đồng Nguyên",
    "Phường Thuận Thành",
    "Phường Mão Điền",
    "Phường Trí Quả",
    "Phường Trạm Lộ",
    "Phường Song Liễu",
    "Phường Ninh Xá",
    "Xã Xuân Lương",
    "Xã Tam Tiến",
    "Xã Đồng Kỳ",
    "Xã Yên Thế",
    "Xã Bố Hạ",
    "Xã Nhã Nam",
    "Xã Phúc Hòa",
    "Xã Quang Trung",
    "Xã Tân Yên",
    "Xã Ngọc Thiện",
    "Xã Lạng Giang",
    "Xã Tiên Lục",
    "Xã Kép",
    "Xã Tân Dĩnh",
    "Xã Lục Nam",
    "Xã Đông Phú",
    "Xã Bảo Đài",
    "Xã Nghĩa Phương",
    "Xã Trường Sơn",
    "Xã Lục Sơn",
    "Xã Bắc Lũng",
    "Xã Cẩm Lý",
    "Xã Tân Sơn",
    "Xã Sa Lý",
    "Xã Biên Sơn",
    "Xã Sơn Hải",
    "Xã Kiên Lao",
    "Xã Biển Động",
    "Xã Lục Ngạn",
    "Xã Đèo Gia",
    "Xã Nam Dương",
    "Xã Sơn Động",
    "Xã Tây Yên Tử",
    "Xã Vân Sơn",
    "Xã Đại Sơn",
    "Xã Yên Định",
    "Xã An Lạc",
    "Xã Tuấn Đạo",
    "Xã Dương Hưu",
    "Xã Đồng Việt",
    "Xã Hoàng Vân",
    "Xã Hiệp Hòa",
    "Xã Hợp Thịnh",
    "Xã Xuân Cẩm",
    "Xã Yên Phong",
    "Xã Tam Giang",
    "Xã Yên Trung",
    "Xã Tam Đa",
    "Xã Văn Môn",
    "Xã Phù Lãng",
    "Xã Chi Lăng",
    "Xã Tiên Du",
    "Xã Liên Bão",
    "Xã Đại Đồng",
    "Xã Tân Chi",
    "Xã Phật Tích",
    "Xã Gia Bình",
    "Xã Cao Đức",
    "Xã Đại Lai",
    "Xã Nhân Thắng",
    "Xã Đông Cứu",
    "Xã Lương Tài",
    "Xã Trung Kênh",
    "Xã Trung Chính",
    "Xã Lâm Thao"
  ],
  "Tỉnh Phú Thọ": [
    "Xã Kim Bôi",
    "Phường Tân Hòa",
    "Phường Hòa Bình",
    "Phường Thống Nhất",
    "Phường Kỳ Sơn",
    "Phường Nông Trang",
    "Phường Việt Trì",
    "Phường Thanh Miếu",
    "Phường Vân Phú",
    "Phường Phú Thọ",
    "Phường Âu Cơ",
    "Phường Phong Châu",
    "Phường Vĩnh Yên",
    "Phường Vĩnh Phúc",
    "Phường Phúc Yên",
    "Phường Xuân Hòa",
    "Xã Đà Bắc",
    "Xã Đức Nhàn",
    "Xã Tân Pheo",
    "Xã Quy Đức",
    "Xã Cao Sơn",
    "Xã Tiền Phong",
    "Xã Thịnh Minh",
    "Xã Lương Sơn",
    "Xã Liên Sơn",
    "Xã Nật Sơn",
    "Xã Mường Động",
    "Xã Cao Dương",
    "Xã Hợp Kim",
    "Xã Dũng Tiến",
    "Xã Cao Phong",
    "Xã Thung Nai",
    "Xã Mường Thàng",
    "Xã Tân Lạc",
    "Xã Mường Hoa",
    "Xã Vân Sơn",
    "Xã Mường Bi",
    "Xã Toàn Thắng",
    "Xã Mai Châu",
    "Xã Tân Mai",
    "Xã Pà Cò",
    "Xã Bao La",
    "Xã Mai Hạ",
    "Xã Lạc Sơn",
    "Xã Mường Vang",
    "Xã Nhân Nghĩa",
    "Xã Thượng Cốc",
    "Xã Yên Phú",
    "Xã Quyết Thắng",
    "Xã Ngọc Sơn",
    "Xã Đại Đồng",
    "Xã Yên Thủy",
    "Xã Lạc Lương",
    "Xã Yên Trị",
    "Xã Lạc Thủy",
    "Xã An Nghĩa",
    "Xã An Bình",
    "Xã Đoan Hùng",
    "Xã Bằng Luân",
    "Xã Chí Đám",
    "Xã Tây Cốc",
    "Xã Chân Mộng",
    "Xã Hạ Hòa",
    "Xã Đan Thượng",
    "Xã Hiền Lương",
    "Xã Yên Kỳ",
    "Xã Văn Lang",
    "Xã Vĩnh Chân",
    "Xã Thanh Ba",
    "Xã Quảng Yên",
    "Xã Hoàng Cương",
    "Xã Đông Thành",
    "Xã Chí Tiên",
    "Xã Liên Minh",
    "Xã Phù Ninh",
    "Xã Phú Mỹ",
    "Xã Trạm Thản",
    "Xã Dân Chủ",
    "Xã Bình Phú",
    "Xã Yên Lập",
    "Xã Sơn Lương",
    "Xã Xuân Viên",
    "Xã Trung Sơn",
    "Xã Thượng Long",
    "Xã Minh Hòa",
    "Xã Cẩm Khê",
    "Xã Tiên Lương",
    "Xã Vân Bán",
    "Xã Phú Khê",
    "Xã Hùng Việt",
    "Xã Đồng Lương",
    "Xã Tam Nông",
    "Xã Hiền Quan",
    "Xã Vạn Xuân",
    "Xã Thọ Văn",
    "Xã Lâm Thao",
    "Xã Xuân Lũng",
    "Xã Hy Cương",
    "Xã Phùng Nguyên",
    "Xã Bản Nguyên",
    "Xã Thanh Sơn",
    "Xã Thu Cúc",
    "Xã Lai Đồng",
    "Xã Tân Sơn",
    "Xã Võ Miếu",
    "Xã Xuân Đài",
    "Xã Minh Đài",
    "Xã Văn Miếu",
    "Xã Cự Đồng",
    "Xã Long Cốc",
    "Xã Hương Cần",
    "Xã Khả Cửu",
    "Xã Yên Sơn",
    "Xã Đào Xá",
    "Xã Thanh Thủy",
    "Xã Tu Vũ",
    "Xã Lập Thạch",
    "Xã Hợp Lý",
    "Xã Yên Lãng",
    "Xã Hải Lựu",
    "Xã Thái Hòa",
    "Xã Liên Hòa",
    "Xã Tam Sơn",
    "Xã Tiên Lữ",
    "Xã Sông Lô",
    "Xã Sơn Đông",
    "Xã Tam Dương",
    "Xã Tam Dương Bắc",
    "Xã Hoàng An",
    "Xã Hội Thịnh",
    "Xã Tam Đảo",
    "Xã Đạo Trù",
    "Xã Đại Đình",
    "Xã Bình Nguyên",
    "Xã Bình Tuyền",
    "Xã Bình Xuyên",
    "Xã Xuân Lãng",
    "Xã Yên Lạc",
    "Xã Tề Lỗ",
    "Xã Tam Hồng",
    "Xã Nguyệt Đức",
    "Xã Liên Châu",
    "Xã Vĩnh Tường",
    "Xã Vĩnh An",
    "Xã Vĩnh Hưng",
    "Xã Vĩnh Thành",
    "Xã Thổ Tang",
    "Xã Vĩnh Phú"
  ],
  "Thành phố Hải Phòng": [
    "Phường Thành Đông",
    "Phường Hải Dương",
    "Phường Lê Thanh Nghị",
    "Phường Tân Hưng",
    "Phường Việt Hòa",
    "Phường Chí Linh",
    "Phường Chu Văn An",
    "Phường Nguyễn Trãi",
    "Phường Trần Hưng Đạo",
    "Phường Trần Nhân Tông",
    "Phường Lê Đại Hành",
    "Phường Ái Quốc",
    "Phường Kinh Môn",
    "Phường Bắc An Phụ",
    "Phường Nhị Chiểu",
    "Phường Phạm Sư Mạnh",
    "Phường Trần Liễu",
    "Phường Nguyễn Đại Năng",
    "Phường Nam Đồng",
    "Phường Tứ Minh",
    "Phường Thạch Khôi",
    "Phường Hồng Bàng",
    "Phường Ngô Quyền",
    "Phường Gia Viên",
    "Phường Lê Chân",
    "Phường An Biên",
    "Phường Đông Hải",
    "Phường Hải An",
    "Phường Kiến An",
    "Phường Phù Liễn",
    "Phường Đồ Sơn",
    "Phường Bạch Đằng",
    "Phường Lưu Kiếm",
    "Phường Lê Ích Mộc",
    "Phường Hòa Bình",
    "Phường Nam Triệu",
    "Phường Thiên Hương",
    "Phường Thủy Nguyên",
    "Phường An Dương",
    "Phường An Phong",
    "Phường Hồng An",
    "Phường An Hải",
    "Phường Hưng Đạo",
    "Phường Dương Kinh",
    "Phường Nam Đồ Sơn",
    "Xã Nam Sách",
    "Xã Hợp Tiến",
    "Xã Trần Phú",
    "Xã Thái Tân",
    "Xã An Phú",
    "Xã Nam An Phụ",
    "Xã Phú Thái",
    "Xã Lai Khê",
    "Xã An Thành",
    "Xã Kim Thành",
    "Xã Thanh Hà",
    "Xã Hà Bắc",
    "Xã Hà Nam",
    "Xã Hà Tây",
    "Xã Hà Đông",
    "Xã Cẩm Giang",
    "Xã Cẩm Giàng",
    "Xã Tuệ Tĩnh",
    "Xã Mao Điền",
    "Xã Kẻ Sặt",
    "Xã Bình Giang",
    "Xã Đường An",
    "Xã Thượng Hồng",
    "Xã Gia Lộc",
    "Xã Yết Kiêu",
    "Xã Gia Phúc",
    "Xã Trường Tân",
    "Xã Tứ Kỳ",
    "Xã Đại Sơn",
    "Xã Tân Kỳ",
    "Xã Chí Minh",
    "Xã Lạc Phượng",
    "Xã Nguyên Giáp",
    "Xã Vĩnh Lại",
    "Xã Tân An",
    "Xã Ninh Giang",
    "Xã Hồng Châu",
    "Xã Khúc Thừa Dụ",
    "Xã Thanh Miện",
    "Xã Nguyễn Lương Bằng",
    "Xã Bắc Thanh Miện",
    "Xã Hải Hưng",
    "Xã Nam Thanh Miện",
    "Xã Việt Khê",
    "Xã An Lão",
    "Xã An Trường",
    "Xã An Quang",
    "Xã An Khánh",
    "Xã An Hưng",
    "Xã Kiến Thụy",
    "Xã Nghi Dương",
    "Xã Kiến Minh",
    "Xã Kiến Hưng",
    "Xã Kiến Hải",
    "Xã Tiên Lãng",
    "Xã Quyết Thắng",
    "Xã Tân Minh",
    "Xã Tiên Minh",
    "Xã Chấn Hưng",
    "Xã Hùng Thắng",
    "Xã Vĩnh Bảo",
    "Xã Vĩnh Thịnh",
    "Xã Vĩnh Thuận",
    "Xã Vĩnh Hòa",
    "Xã Vĩnh Hải",
    "Xã Vĩnh Am",
    "Xã Nguyễn Bỉnh Khiêm",
    "Đặc khu Cát Hải",
    "Đặc khu Bạch Long Vĩ"
  ],
  "Tỉnh Hưng Yên": [
    "Phường Phố Hiến",
    "Phường Hồng Châu",
    "Phường Sơn Nam",
    "Phường Mỹ Hào",
    "Phường Thượng Hồng",
    "Phường Đường Hào",
    "Phường Trần Hưng Đạo",
    "Phường Trần Lãm",
    "Phường Vũ Phúc",
    "Phường Trà Lý",
    "Phường Thái Bình",
    "Xã Tân Hưng",
    "Xã Lạc Đạo",
    "Xã Đại Đồng",
    "Xã Như Quỳnh",
    "Xã Văn Giang",
    "Xã Phụng Công",
    "Xã Nghĩa Trụ",
    "Xã Mễ Sở",
    "Xã Nguyễn Văn Linh",
    "Xã Hoàn Long",
    "Xã Yên Mỹ",
    "Xã Việt Yên",
    "Xã Ân Thi",
    "Xã Phạm Ngũ Lão",
    "Xã Xuân Trúc",
    "Xã Nguyễn Trãi",
    "Xã Hồng Quang",
    "Xã Khoái Châu",
    "Xã Triệu Việt Vương",
    "Xã Việt Tiến",
    "Xã Châu Ninh",
    "Xã Chí Minh",
    "Xã Lương Bằng",
    "Xã Nghĩa Dân",
    "Xã Đức Hợp",
    "Xã Hiệp Cường",
    "Xã Hoàng Hoa Thám",
    "Xã Tiên Hoa",
    "Xã Tiên Lữ",
    "Xã Quang Hưng",
    "Xã Đoàn Đào",
    "Xã Tiên Tiến",
    "Xã Tống Trân",
    "Xã Quỳnh Phụ",
    "Xã A Sào",
    "Xã Minh Thọ",
    "Xã Ngọc Lâm",
    "Xã Phụ Dực",
    "Xã Đồng Bằng",
    "Xã Nguyễn Du",
    "Xã Quỳnh An",
    "Xã Tân Tiến",
    "Xã Hưng Hà",
    "Xã Ngự Thiên",
    "Xã Long Hưng",
    "Xã Diên Hà",
    "Xã Thần Khê",
    "Xã Tiên La",
    "Xã Lê Quý Đôn",
    "Xã Hồng Minh",
    "Xã Đông Hưng",
    "Xã Bắc Đông Hưng",
    "Xã Bắc Tiên Hưng",
    "Xã Đông Tiên Hưng",
    "Xã Bắc Đông Quan",
    "Xã Tiên Hưng",
    "Xã Nam Tiên Hưng",
    "Xã Nam Đông Hưng",
    "Xã Đông Quan",
    "Xã Thái Thụy",
    "Xã Tây Thụy Anh",
    "Xã Bắc Thụy Anh",
    "Xã Đông Thụy Anh",
    "Xã Thụy Anh",
    "Xã Nam Thụy Anh",
    "Xã Bắc Thái Ninh",
    "Xã Tây Thái Ninh",
    "Xã Thái Ninh",
    "Xã Đông Thái Ninh",
    "Xã Nam Thái Ninh",
    "Xã Tiền Hải",
    "Xã Đông Tiền Hải",
    "Xã Đồng Châu",
    "Xã Ái Quốc",
    "Xã Tây Tiền Hải",
    "Xã Nam Cường",
    "Xã Nam Tiền Hải",
    "Xã Hưng Phú",
    "Xã Kiến Xương",
    "Xã Trà Giang",
    "Xã Bình Nguyên",
    "Xã Lê Lợi",
    "Xã Quang Lịch",
    "Xã Vũ Quý",
    "Xã Hồng Vũ",
    "Xã Bình Thanh",
    "Xã Bình Định",
    "Xã Vũ Thư",
    "Xã Vạn Xuân",
    "Xã Thư Trì",
    "Xã Tân Thuận",
    "Xã Thư Vũ",
    "Xã Vũ Tiên"
  ],
  "Tỉnh Ninh Bình": [
    "Phường Phủ Lý",
    "Phường Phù Vân",
    "Phường Châu Sơn",
    "Phường Duy Tiên",
    "Phường Duy Tân",
    "Phường Duy Hà",
    "Phường Đồng Văn",
    "Phường Tiên Sơn",
    "Phường Hà Nam",
    "Phường Kim Bảng",
    "Phường Lê Hồ",
    "Phường Nguyễn Úy",
    "Phường Kim Thanh",
    "Phường Tam Chúc",
    "Phường Lý Thường Kiệt",
    "Phường Liêm Tuyền",
    "Phường Nam Định",
    "Phường Thiên Trường",
    "Phường Đông A",
    "Phường Thành Nam",
    "Phường Mỹ Lộc",
    "Phường Trường Thi",
    "Phường Vị Khê",
    "Phường Hồng Quang",
    "Phường Hoa Lư",
    "Phường Nam Hoa Lư",
    "Phường Tam Điệp",
    "Phường Trung Sơn",
    "Phường Yên Sơn",
    "Phường Tây Hoa Lư",
    "Phường Đông Hoa Lư",
    "Phường Yên Thắng",
    "Xã Liêm Hà",
    "Xã Tân Thanh",
    "Xã Thanh Bình",
    "Xã Thanh Lâm",
    "Xã Thanh Liêm",
    "Xã Bình Mỹ",
    "Xã Bình Lục",
    "Xã Bình Giang",
    "Xã Bình An",
    "Xã Bình Sơn",
    "Xã Lý Nhân",
    "Xã Bắc Lý",
    "Xã Nam Xang",
    "Xã Trần Thương",
    "Xã Vĩnh Trụ",
    "Xã Nhân Hà",
    "Xã Nam Lý",
    "Xã Vụ Bản",
    "Xã Minh Tân",
    "Xã Hiển Khánh",
    "Xã Liên Minh",
    "Xã Ý Yên",
    "Xã Tân Minh",
    "Xã Phong Doanh",
    "Xã Vũ Dương",
    "Xã Vạn Thắng",
    "Xã Yên Cường",
    "Xã Yên Đồng",
    "Xã Nghĩa Hưng",
    "Xã Rạng Đông",
    "Xã Đồng Thịnh",
    "Xã Nghĩa Sơn",
    "Xã Hồng Phong",
    "Xã Quỹ Nhất",
    "Xã Nghĩa Lâm",
    "Xã Nam Trực",
    "Xã Nam Hồng",
    "Xã Nam Ninh",
    "Xã Nam Minh",
    "Xã Nam Đồng",
    "Xã Cổ Lễ",
    "Xã Ninh Giang",
    "Xã Trực Ninh",
    "Xã Cát Thành",
    "Xã Quang Hưng",
    "Xã Minh Thái",
    "Xã Ninh Cường",
    "Xã Xuân Trường",
    "Xã Xuân Hồng",
    "Xã Xuân Giang",
    "Xã Xuân Hưng",
    "Xã Giao Minh",
    "Xã Giao Thủy",
    "Xã Giao Hưng",
    "Xã Giao Hòa",
    "Xã Giao Bình",
    "Xã Giao Phúc",
    "Xã Giao Ninh",
    "Xã Hải Hậu",
    "Xã Hải Tiến",
    "Xã Hải Thịnh",
    "Xã Hải Anh",
    "Xã Hải Hưng",
    "Xã Hải An",
    "Xã Hải Quang",
    "Xã Hải Xuân",
    "Xã Gia Lâm",
    "Xã Gia Tường",
    "Xã Cúc Phương",
    "Xã Phú Sơn",
    "Xã Nho Quan",
    "Xã Thanh Sơn",
    "Xã Quỳnh Lưu",
    "Xã Phú Long",
    "Xã Gia Viễn",
    "Xã Gia Hưng",
    "Xã Gia Vân",
    "Xã Gia Trấn",
    "Xã Đại Hoàng",
    "Xã Gia Phong",
    "Xã Yên Khánh",
    "Xã Khánh Thiện",
    "Xã Khánh Trung",
    "Xã Khánh Nhạc",
    "Xã Khánh Hội",
    "Xã Phát Diệm",
    "Xã Bình Minh",
    "Xã Kim Sơn",
    "Xã Quang Thiện",
    "Xã Chất Bình",
    "Xã Lai Thành",
    "Xã Định Hóa",
    "Xã Kim Đông",
    "Xã Yên Mô",
    "Xã Yên Từ",
    "Xã Yên Mạc",
    "Xã Đồng Thái"
  ],
  "Tỉnh Thanh Hóa": [
    "Phường Hàm Rồng",
    "Phường Hạc Thành",
    "Phường Bỉm Sơn",
    "Phường Quang Trung",
    "Phường Đông Tiến",
    "Phường Nguyệt Viên",
    "Phường Đông Sơn",
    "Phường Đông Quang",
    "Phường Nam Sầm Sơn",
    "Phường Quảng Phú",
    "Phường Sầm Sơn",
    "Phường Tĩnh Gia",
    "Phường Ngọc Sơn",
    "Phường Tân Dân",
    "Phường Hải Lĩnh",
    "Phường Đào Duy Từ",
    "Phường Trúc Lâm",
    "Phường Hải Bình",
    "Phường Nghi Sơn",
    "Xã Mường Lát",
    "Xã Tam Chung",
    "Xã Mường Lý",
    "Xã Trung Lý",
    "Xã Quang Chiểu",
    "Xã Pù Nhi",
    "Xã Nhi Sơn",
    "Xã Mường Chanh",
    "Xã Hồi Xuân",
    "Xã Trung Thành",
    "Xã Trung Sơn",
    "Xã Phú Lệ",
    "Xã Phú Xuân",
    "Xã Hiền Kiệt",
    "Xã Nam Xuân",
    "Xã Thiên Phủ",
    "Xã Bá Thước",
    "Xã Điền Quang",
    "Xã Điền Lư",
    "Xã Quý Lương",
    "Xã Pù Luông",
    "Xã Cổ Lũng",
    "Xã Văn Nho",
    "Xã Thiết Ống",
    "Xã Trung Hạ",
    "Xã Tam Thanh",
    "Xã Sơn Thủy",
    "Xã Na Mèo",
    "Xã Quan Sơn",
    "Xã Tam Lư",
    "Xã Sơn Điện",
    "Xã Mường Mìn",
    "Xã Yên Khương",
    "Xã Yên Thắng",
    "Xã Giao An",
    "Xã Văn Phú",
    "Xã Linh Sơn",
    "Xã Đồng Lương",
    "Xã Ngọc Lặc",
    "Xã Thạch Lập",
    "Xã Ngọc Liên",
    "Xã Nguyệt Ấn",
    "Xã Kiên Thọ",
    "Xã Minh Sơn",
    "Xã Cẩm Thủy",
    "Xã Cẩm Thạch",
    "Xã Cẩm Tú",
    "Xã Cẩm Vân",
    "Xã Cẩm Tân",
    "Xã Kim Tân",
    "Xã Vân Du",
    "Xã Thạch Quảng",
    "Xã Thạch Bình",
    "Xã Thành Vinh",
    "Xã Ngọc Trạo",
    "Xã Hà Trung",
    "Xã Hà Long",
    "Xã Hoạt Giang",
    "Xã Lĩnh Toại",
    "Xã Tống Sơn",
    "Xã Vĩnh Lộc",
    "Xã Tây Đô",
    "Xã Biện Thượng",
    "Xã Yên Phú",
    "Xã Quý Lộc",
    "Xã Yên Trường",
    "Xã Yên Ninh",
    "Xã Định Hòa",
    "Xã Định Tân",
    "Xã Yên Định",
    "Xã Thọ Xuân",
    "Xã Thọ Long",
    "Xã Xuân Hòa",
    "Xã Lam Sơn",
    "Xã Sao Vàng",
    "Xã Thọ Lập",
    "Xã Xuân Tín",
    "Xã Xuân Lập",
    "Xã Bát Mọt",
    "Xã Yên Nhân",
    "Xã Vạn Xuân",
    "Xã Lương Sơn",
    "Xã Luận Thành",
    "Xã Thắng Lộc",
    "Xã Thường Xuân",
    "Xã Xuân Chinh",
    "Xã Tân Thành",
    "Xã Triệu Sơn",
    "Xã Thọ Bình",
    "Xã Hợp Tiến",
    "Xã Tân Ninh",
    "Xã Đồng Tiến",
    "Xã Thọ Ngọc",
    "Xã Thọ Phú",
    "Xã An Nông",
    "Xã Thiệu Hóa",
    "Xã Thiệu Tiến",
    "Xã Thiệu Quang",
    "Xã Thiệu Toán",
    "Xã Thiệu Trung",
    "Xã Hoằng Hóa",
    "Xã Hoằng Giang",
    "Xã Hoằng Phú",
    "Xã Hoằng Sơn",
    "Xã Hoằng Lộc",
    "Xã Hoằng Châu",
    "Xã Hoằng Tiến",
    "Xã Hoằng Thanh",
    "Xã Hậu Lộc",
    "Xã Triệu Lộc",
    "Xã Đông Thành",
    "Xã Hoa Lộc",
    "Xã Vạn Lộc",
    "Xã Nga Sơn",
    "Xã Tân Tiến",
    "Xã Nga Thắng",
    "Xã Hồ Vương",
    "Xã Nga An",
    "Xã Ba Đình",
    "Xã Như Xuân",
    "Xã Xuân Bình",
    "Xã Hóa Quỳ",
    "Xã Thanh Phong",
    "Xã Thanh Quân",
    "Xã Thượng Ninh",
    "Xã Như Thanh",
    "Xã Xuân Du",
    "Xã Mậu Lâm",
    "Xã Xuân Thái",
    "Xã Yên Thọ",
    "Xã Thanh Kỳ",
    "Xã Nông Cống",
    "Xã Trung Chính",
    "Xã Thắng Lợi",
    "Xã Thăng Bình",
    "Xã Trường Văn",
    "Xã Tượng Lĩnh",
    "Xã Công Chính",
    "Xã Lưu Vệ",
    "Xã Quảng Yên",
    "Xã Quảng Chính",
    "Xã Quảng Ngọc",
    "Xã Quảng Ninh",
    "Xã Quảng Bình",
    "Xã Tiên Trang",
    "Xã Các Sơn",
    "Xã Trường Lâm"
  ],
  "Tỉnh Nghệ An": [
    "Phường Thành Vinh",
    "Phường Trường Vinh",
    "Phường Vinh Phú",
    "Phường Vinh Lộc",
    "Phường Cửa Lò",
    "Phường Thái Hòa",
    "Phường Tây Hiếu",
    "Phường Hoàng Mai",
    "Phường Quỳnh Mai",
    "Phường Tân Mai",
    "Phường Vinh Hưng",
    "Xã Quế Phong",
    "Xã Thông Thụ",
    "Xã Tiền Phong",
    "Xã Tri Lễ",
    "Xã Mường Quàng",
    "Xã Quỳ Châu",
    "Xã Châu Tiến",
    "Xã Hùng Chân",
    "Xã Châu Bình",
    "Xã Mường Xén",
    "Xã Mỹ Lý",
    "Xã Bắc Lý",
    "Xã Keng Đu",
    "Xã Huồi Tụ",
    "Xã Mường Lống",
    "Xã Na Loi",
    "Xã Nậm Cắn",
    "Xã Hữu Kiệm",
    "Xã Chiêu Lưu",
    "Xã Mường Típ",
    "Xã Na Ngoi",
    "Xã Tương Dương",
    "Xã Nhôn Mai",
    "Xã Hữu Khuông",
    "Xã Nga My",
    "Xã Lượng Minh",
    "Xã Yên Hòa",
    "Xã Yên Na",
    "Xã Tam Quang",
    "Xã Tam Thái",
    "Xã Nghĩa Đàn",
    "Xã Nghĩa Lâm",
    "Xã Nghĩa Thọ",
    "Xã Nghĩa Hưng",
    "Xã Nghĩa Mai",
    "Xã Đông Hiếu",
    "Xã Nghĩa Lộc",
    "Xã Nghĩa Khánh",
    "Xã Quỳ Hợp",
    "Xã Châu Hồng",
    "Xã Châu Lộc",
    "Xã Tam Hợp",
    "Xã Minh Hợp",
    "Xã Mường Ham",
    "Xã Mường Chọng",
    "Xã Quỳnh Văn",
    "Xã Quỳnh Tam",
    "Xã Quỳnh Sơn",
    "Xã Quỳnh Anh",
    "Xã Quỳnh Lưu",
    "Xã Quỳnh Phú",
    "Xã Quỳnh Thắng",
    "Xã Bình Chuẩn",
    "Xã Mậu Thạch",
    "Xã Cam Phục",
    "Xã Châu Khê",
    "Xã Con Cuông",
    "Xã Môn Sơn",
    "Xã Tân Kỳ",
    "Xã Tân Phú",
    "Xã Giai Xuân",
    "Xã Nghĩa Đồng",
    "Xã Tiên Đồng",
    "Xã Tân An",
    "Xã Nghĩa Hành",
    "Xã Anh Sơn",
    "Xã Thành Bình Thọ",
    "Xã Nhân Hòa",
    "Xã Vĩnh Tường",
    "Xã Anh Sơn Đông",
    "Xã Yên Xuân",
    "Xã Hùng Châu",
    "Xã Đức Châu",
    "Xã Hải Châu",
    "Xã Quảng Châu",
    "Xã Diễn Châu",
    "Xã Minh Châu",
    "Xã An Châu",
    "Xã Tân Châu",
    "Xã Yên Thành",
    "Xã Bình Minh",
    "Xã Quang Đồng",
    "Xã Giai Lạc",
    "Xã Đông Thành",
    "Xã Vân Du",
    "Xã Quan Thành",
    "Xã Hợp Minh",
    "Xã Vân Tụ",
    "Xã Bạch Ngọc",
    "Xã Lương Sơn",
    "Xã Đô Lương",
    "Xã Văn Hiến",
    "Xã Thuần Trung",
    "Xã Bạch Hà",
    "Xã Đại Đồng",
    "Xã Hạnh Lâm",
    "Xã Cát Ngạn",
    "Xã Tam Đồng",
    "Xã Sơn Lâm",
    "Xã Hoa Quân",
    "Xã Xuân Lâm",
    "Xã Kim Bảng",
    "Xã Bích Hào",
    "Xã Nghi Lộc",
    "Xã Hải Lộc",
    "Xã Thần Lĩnh",
    "Xã Văn Kiều",
    "Xã Phúc Lộc",
    "Xã Trung Lộc",
    "Xã Đông Lộc",
    "Xã Nam Đàn",
    "Xã Đại Huệ",
    "Xã Vạn An",
    "Xã Kim Liên",
    "Xã Thiên Nhẫn",
    "Xã Hưng Nguyên",
    "Xã Yên Trung",
    "Xã Hưng Nguyên Nam",
    "Xã Lam Thành"
  ],
  "Tỉnh Hà Tĩnh": [
    "Phường Thành Sen",
    "Phường Trần Phú",
    "Phường Bắc Hồng Lĩnh",
    "Phường Nam Hồng Lĩnh",
    "Phường Hà Huy Tập",
    "Phường Sông Trí",
    "Phường Hải Ninh",
    "Phường Vũng Áng",
    "Phường Hoành Sơn",
    "Xã Hương Sơn",
    "Xã Sơn Hồng",
    "Xã Sơn Tiến",
    "Xã Sơn Tây",
    "Xã Sơn Giang",
    "Xã Sơn Kim 1",
    "Xã Sơn Kim 2",
    "Xã Tứ Mỹ",
    "Xã Kim Hoa",
    "Xã Đức Thọ",
    "Xã Đức Minh",
    "Xã Đức Quang",
    "Xã Đức Thịnh",
    "Xã Đức Đồng",
    "Xã Vũ Quang",
    "Xã Mai Hoa",
    "Xã Thượng Đức",
    "Xã Nghi Xuân",
    "Xã Đan Hải",
    "Xã Tiên Điền",
    "Xã Cổ Đạm",
    "Xã Can Lộc",
    "Xã Hồng Lộc",
    "Xã Tùng Lộc",
    "Xã Trường Lưu",
    "Xã Gia Hanh",
    "Xã Xuân Lộc",
    "Xã Đồng Lộc",
    "Xã Hương Khê",
    "Xã Hà Linh",
    "Xã Hương Bình",
    "Xã Hương Phố",
    "Xã Hương Xuân",
    "Xã Phúc Trạch",
    "Xã Hương Đô",
    "Xã Thạch Hà",
    "Xã Lộc Hà",
    "Xã Mai Phụ",
    "Xã Đông Kinh",
    "Xã Việt Xuyên",
    "Xã Thạch Khê",
    "Xã Đồng Tiến",
    "Xã Thạch Lạc",
    "Xã Toàn Lưu",
    "Xã Thạch Xuân",
    "Xã Cẩm Xuyên",
    "Xã Thiên Cầm",
    "Xã Yên Hòa",
    "Xã Cẩm Bình",
    "Xã Cẩm Hưng",
    "Xã Cẩm Duệ",
    "Xã Cẩm Trung",
    "Xã Cẩm Lạc",
    "Xã Kỳ Xuân",
    "Xã Kỳ Anh",
    "Xã Kỳ Văn",
    "Xã Kỳ Khang",
    "Xã Kỳ Hoa",
    "Xã Kỳ Lạc",
    "Xã Kỳ Thượng"
  ],
  "Tỉnh Quảng Trị": [
    "Phường Đồng Thuận",
    "Phường Đồng Sơn",
    "Phường Đồng Hới",
    "Phường Ba Đồn",
    "Phường Bắc Gianh",
    "Phường Đông Hà",
    "Phường Nam Đông Hà",
    "Phường Quảng Trị",
    "Xã Minh Hóa",
    "Xã Dân Hóa",
    "Xã Tân Thành",
    "Xã Kim Điền",
    "Xã Kim Phú",
    "Xã Đồng Lê",
    "Xã Tuyên Sơn",
    "Xã Tuyên Lâm",
    "Xã Tuyên Phú",
    "Xã Tuyên Bình",
    "Xã Tuyên Hóa",
    "Xã Phú Trạch",
    "Xã Trung Thuần",
    "Xã Hòa Trạch",
    "Xã Tân Gianh",
    "Xã Quảng Trạch",
    "Xã Nam Ba Đồn",
    "Xã Nam Gianh",
    "Xã Hoàn Lão",
    "Xã Bắc Trạch",
    "Xã Phong Nha",
    "Xã Bố Trạch",
    "Xã Thượng Trạch",
    "Xã Đông Trạch",
    "Xã Nam Trạch",
    "Xã Trường Sơn",
    "Xã Quảng Ninh",
    "Xã Ninh Châu",
    "Xã Trường Ninh",
    "Xã Lệ Ninh",
    "Xã Lệ Thủy",
    "Xã Cam Hồng",
    "Xã Sen Ngư",
    "Xã Tân Mỹ",
    "Xã Trường Phú",
    "Xã Kim Ngân",
    "Xã Vĩnh Linh",
    "Xã Bến Quan",
    "Xã Vĩnh Hoàng",
    "Xã Vĩnh Thủy",
    "Xã Cửa Tùng",
    "Xã Khe Sanh",
    "Xã Lao Bảo",
    "Xã Hướng Lập",
    "Xã Hướng Phùng",
    "Xã Tân Lập",
    "Xã A Dơi",
    "Xã Lìa",
    "Xã Gio Linh",
    "Xã Cửa Việt",
    "Xã Bến Hải",
    "Xã Cồn Tiên",
    "Xã Hướng Hiệp",
    "Xã Đakrông",
    "Xã Ba Lòng",
    "Xã Tà Rụt",
    "Xã La Lay",
    "Xã Cam Lộ",
    "Xã Hiếu Giang",
    "Xã Triệu Phong",
    "Xã Nam Cửa Việt",
    "Xã Triệu Bình",
    "Xã Triệu Cơ",
    "Xã Ái Tử",
    "Xã Diên Sanh",
    "Xã Vĩnh Định",
    "Xã Hải Lăng",
    "Xã Nam Hải Lăng",
    "Xã Mỹ Thủy",
    "Đặc khu Cồn Cỏ"
  ],
  "Thành phố Huế": [
    "Phường Phú Xuân",
    "Phường Kim Long",
    "Phường Vỹ Dạ",
    "Phường Thuận Hóa",
    "Phường Hương An",
    "Phường Thủy Xuân",
    "Phường An Cựu",
    "Phường Phong Điền",
    "Phường Phong Phú",
    "Phường Phong Dinh",
    "Phường Phong Thái",
    "Phường Phong Quảng",
    "Phường Thuận An",
    "Phường Dương Nỗ",
    "Phường Mỹ Thượng",
    "Phường Phú Bài",
    "Phường Thanh Thủy",
    "Phường Hương Thủy",
    "Phường Hương Trà",
    "Phường Hóa Châu",
    "Phường Kim Trà",
    "Xã Quảng Điền",
    "Xã Đan Điền",
    "Xã Phú Hồ",
    "Xã Phú Vang",
    "Xã Phú Vinh",
    "Xã Bình Điền",
    "Xã A Lưới 2",
    "Xã A Lưới 5",
    "Xã A Lưới 1",
    "Xã A Lưới 3",
    "Xã A Lưới 4",
    "Xã Phú Lộc",
    "Xã Vinh Lộc",
    "Xã Hưng Lộc",
    "Xã Chân Mây - Lăng Cô",
    "Xã Lộc An",
    "Xã Khe Tre",
    "Xã Nam Đông",
    "Xã Long Quảng"
  ],
  "Thành phố Đà Nẵng": [
    "Phường Hải Vân",
    "Phường Liên Chiểu",
    "Phường Hòa Khánh",
    "Phường Thanh Khê",
    "Phường Hải Châu",
    "Phường Hòa Cường",
    "Phường Cẩm Lệ",
    "Phường Sơn Trà",
    "Phường An Hải",
    "Phường Ngũ Hành Sơn",
    "Phường An Khê",
    "Phường Hòa Xuân",
    "Phường Bàn Thạch",
    "Phường Tam Kỳ",
    "Phường Hương Trà",
    "Phường Quảng Phú",
    "Phường Hội An Tây",
    "Phường Hội An",
    "Phường Hội An Đông",
    "Phường Điện Bàn",
    "Phường Điện Bàn Bắc",
    "Phường An Thắng",
    "Phường Điện Bàn Đông",
    "Xã Bà Nà",
    "Xã Hòa Vang",
    "Xã Hòa Tiến",
    "Xã Chiên Đàn",
    "Xã Tây Hồ",
    "Xã Phú Ninh",
    "Xã Tân Hiệp",
    "Xã Hùng Sơn",
    "Xã Tây Giang",
    "Xã Avương",
    "Xã Đông Giang",
    "Xã Sông Kôn",
    "Xã Sông Vàng",
    "Xã Bến Hiên",
    "Xã Đại Lộc",
    "Xã Thượng Đức",
    "Xã Hà Nha",
    "Xã Vu Gia",
    "Xã Phú Thuận",
    "Xã Điện Bàn Tây",
    "Xã Gò Nổi",
    "Xã Nam Phước",
    "Xã Thu Bồn",
    "Xã Duy Xuyên",
    "Xã Duy Nghĩa",
    "Xã Quế Sơn",
    "Xã Xuân Phú",
    "Xã Nông Sơn",
    "Xã Quế Sơn Trung",
    "Xã Quế Phước",
    "Xã Thạnh Mỹ",
    "Xã La Êê",
    "Xã La Dêê",
    "Xã Nam Giang",
    "Xã Bến Giằng",
    "Xã Đắc Pring",
    "Xã Khâm Đức",
    "Xã Phước Hiệp",
    "Xã Phước Năng",
    "Xã Phước Chánh",
    "Xã Phước Thành",
    "Xã Việt An",
    "Xã Phước Trà",
    "Xã Hiệp Đức",
    "Xã Thăng Bình",
    "Xã Thăng An",
    "Xã Đồng Dương",
    "Xã Thăng Phú",
    "Xã Thăng Trường",
    "Xã Thăng Điền",
    "Xã Tiên Phước",
    "Xã Sơn Cẩm Hà",
    "Xã Lãnh Ngọc",
    "Xã Thạnh Bình",
    "Xã Trà My",
    "Xã Trà Liên",
    "Xã Trà Đốc",
    "Xã Trà Tân",
    "Xã Trà Giáp",
    "Xã Trà Leng",
    "Xã Trà Tập",
    "Xã Nam Trà My",
    "Xã Trà Linh",
    "Xã Trà Vân",
    "Xã Núi Thành",
    "Xã Tam Xuân",
    "Xã Đức Phú",
    "Xã Tam Anh",
    "Xã Tam Hải",
    "Xã Tam Mỹ",
    "Đặc khu Hoàng Sa"
  ],
  "Tỉnh Quảng Ngãi": [
    "Phường Cẩm Thành",
    "Phường Nghĩa Lộ",
    "Phường Trương Quang Trọng",
    "Phường Đức Phổ",
    "Phường Trà Câu",
    "Phường Sa Huỳnh",
    "Phường Đăk Cấm",
    "Phường Kon Tum",
    "Phường Đăk Bla",
    "Xã An Phú",
    "Xã Bình Sơn",
    "Xã Vạn Tường",
    "Xã Bình Minh",
    "Xã Bình Chương",
    "Xã Đông Sơn",
    "Xã Trà Bồng",
    "Xã Thanh Bồng",
    "Xã Đông Trà Bồng",
    "Xã Cà Đam",
    "Xã Tây Trà",
    "Xã Tây Trà Bồng",
    "Xã Thọ Phong",
    "Xã Trường Giang",
    "Xã Ba Gia",
    "Xã Tịnh Khê",
    "Xã Sơn Tịnh",
    "Xã Tư Nghĩa",
    "Xã Vệ Giang",
    "Xã Trà Giang",
    "Xã Nghĩa Giang",
    "Xã Sơn Hà",
    "Xã Sơn Hạ",
    "Xã Sơn Linh",
    "Xã Sơn Thủy",
    "Xã Sơn Kỳ",
    "Xã Sơn Tây Thượng",
    "Xã Sơn Tây",
    "Xã Sơn Tây Hạ",
    "Xã Sơn Mai",
    "Xã Minh Long",
    "Xã Nghĩa Hành",
    "Xã Phước Giang",
    "Xã Đình Cương",
    "Xã Thiện Tín",
    "Xã Mộ Đức",
    "Xã Long Phụng",
    "Xã Mỏ Cày",
    "Xã Lân Phong",
    "Xã Nguyễn Nghiêm",
    "Xã Khánh Cường",
    "Xã Ba Tơ",
    "Xã Ba Vinh",
    "Xã Ba Động",
    "Xã Ba Dinh",
    "Xã Đặng Thùy Trâm",
    "Xã Ba Tô",
    "Xã Ba Vì",
    "Xã Ba Xa",
    "Xã Ngọk Bay",
    "Xã Ia Chim",
    "Xã Đăk Rơ Wa",
    "Xã Đăk Pék",
    "Xã Đăk Plô",
    "Xã Xốp",
    "Xã Ngọc Linh",
    "Xã Đăk Long",
    "Xã Đăk Môn",
    "Xã Bờ Y",
    "Xã Dục Nông",
    "Xã Sa Loong",
    "Xã Đăk Tô",
    "Xã Đăk Sao",
    "Xã Đăk Tờ Kan",
    "Xã Tu Mơ Rông",
    "Xã Ngọk Tụ",
    "Xã Kon Đào",
    "Xã Măng Ri",
    "Xã Măng Bút",
    "Xã Măng Đen",
    "Xã Kon Plông",
    "Xã Đăk Rve",
    "Xã Đăk Kôi",
    "Xã Kon Braih",
    "Xã Đăk Hà",
    "Xã Đăk Pxi",
    "Xã Đăk Ui",
    "Xã Đăk Mar",
    "Xã Ngọk Réo",
    "Xã Sa Thầy",
    "Xã Rờ Kơi",
    "Xã Sa Bình",
    "Xã Ia Đal",
    "Xã Mô Rai",
    "Xã Ia Tơi",
    "Xã Ya Ly",
    "Đặc khu Lý Sơn"
  ],
  "Tỉnh Gia Lai": [
    "Phường Quy Nhơn Bắc",
    "Phường Quy Nhơn",
    "Phường Quy Nhơn Tây",
    "Phường Quy Nhơn Nam",
    "Phường Quy Nhơn Đông",
    "Phường Tam Quan",
    "Phường Bồng Sơn",
    "Phường Hoài Nhơn Bắc",
    "Phường Hoài Nhơn Tây",
    "Phường Hoài Nhơn",
    "Phường Hoài Nhơn Đông",
    "Phường Hoài Nhơn Nam",
    "Phường Bình Định",
    "Phường An Nhơn",
    "Phường An Nhơn Bắc",
    "Phường An Nhơn Đông",
    "Phường An Nhơn Nam",
    "Phường Diên Hồng",
    "Phường Pleiku",
    "Phường Thống Nhất",
    "Phường Hội Phú",
    "Phường An Phú",
    "Phường An Bình",
    "Phường An Khê",
    "Phường Ayun Pa",
    "Xã Nhơn Châu",
    "Xã An Lão",
    "Xã An Vinh",
    "Xã An Toàn",
    "Xã An Hòa",
    "Xã Hoài Ân",
    "Xã Ân Hảo",
    "Xã Vạn Đức",
    "Xã Ân Tường",
    "Xã Kim Sơn",
    "Xã Phù Mỹ",
    "Xã Bình Dương",
    "Xã Phù Mỹ Bắc",
    "Xã Phù Mỹ Đông",
    "Xã Phù Mỹ Tây",
    "Xã An Lương",
    "Xã Phù Mỹ Nam",
    "Xã Vĩnh Thạnh",
    "Xã Vĩnh Sơn",
    "Xã Vĩnh Thịnh",
    "Xã Vĩnh Quang",
    "Xã Tây Sơn",
    "Xã Bình Hiệp",
    "Xã Bình Khê",
    "Xã Bình An",
    "Xã Bình Phú",
    "Xã Phù Cát",
    "Xã Đề Gi",
    "Xã Hội Sơn",
    "Xã Hòa Hội",
    "Xã Cát Tiến",
    "Xã Xuân An",
    "Xã Ngô Mây",
    "Xã An Nhơn Tây",
    "Xã Tuy Phước",
    "Xã Tuy Phước Bắc",
    "Xã Tuy Phước Đông",
    "Xã Tuy Phước Tây",
    "Xã Vân Canh",
    "Xã Canh Liên",
    "Xã Canh Vinh",
    "Xã Biển Hồ",
    "Xã Gào",
    "Xã Cửu An",
    "Xã Kbang",
    "Xã Đak Rong",
    "Xã Sơn Lang",
    "Xã Krong",
    "Xã Tơ Tung",
    "Xã Kông Bơ La",
    "Xã Đak Đoa",
    "Xã Đak Sơmei",
    "Xã Kon Gang",
    "Xã Ia Băng",
    "Xã KDang",
    "Xã Chư Păh",
    "Xã Ia Khươl",
    "Xã Ia Ly",
    "Xã Ia Mơ",
    "Xã Ia Phí",
    "Xã Ia Grai",
    "Xã Ia Hrung",
    "Xã Ia Krái",
    "Xã Ia O",
    "Xã Ia Chia",
    "Xã Mang Yang",
    "Xã Ayun",
    "Xã Hra",
    "Xã Lơ Pang",
    "Xã Kon Chiêng",
    "Xã Kông Chro",
    "Xã Chư Krey",
    "Xã Ya Ma",
    "Xã SRó",
    "Xã Đăk Song",
    "Xã Chơ Long",
    "Xã Đức Cơ",
    "Xã Ia Krêl",
    "Xã Ia Dơk",
    "Xã Ia Dom",
    "Xã Ia Pnôn",
    "Xã Ia Nan",
    "Xã Chư Prông",
    "Xã Bàu Cạn",
    "Xã Ia Tôr",
    "Xã Ia Boòng",
    "Xã Ia Púch",
    "Xã Ia Pia",
    "Xã Ia Lâu",
    "Xã Chư Sê",
    "Xã Chư Pưh",
    "Xã Bờ Ngoong",
    "Xã Al Bá",
    "Xã Ia Hrú",
    "Xã Ia Ko",
    "Xã Ia Le",
    "Xã Đak Pơ",
    "Xã Ya Hội",
    "Xã Pờ Tó",
    "Xã Ia Pa",
    "Xã Ia Tul",
    "Xã Phú Thiện",
    "Xã Chư A Thai",
    "Xã Ia Hiao",
    "Xã Ia Rbol",
    "Xã Ia Sao",
    "Xã Phú Túc",
    "Xã Ia Dreh",
    "Xã Uar",
    "Xã Ia Rsai"
  ],
  "Tỉnh Khánh Hòa": [
    "Phường Bắc Nha Trang",
    "Phường Nha Trang",
    "Phường Tây Nha Trang",
    "Phường Nam Nha Trang",
    "Phường Bắc Cam Ranh",
    "Phường Cam Ranh",
    "Phường Ba Ngòi",
    "Phường Cam Linh",
    "Phường Ninh Hòa",
    "Phường Đông Ninh Hòa",
    "Phường Hòa Thắng",
    "Phường Đô Vinh",
    "Phường Bảo An",
    "Phường Phan Rang",
    "Phường Đông Hải",
    "Phường Ninh Chử",
    "Xã Cam Hiệp",
    "Xã Cam Lâm",
    "Xã Cam An",
    "Xã Nam Cam Ranh",
    "Xã Vạn Ninh",
    "Xã Tu Bông",
    "Xã Đại Lãnh",
    "Xã Vạn Thắng",
    "Xã Vạn Hưng",
    "Xã Bắc Ninh Hòa",
    "Xã Tây Ninh Hòa",
    "Xã Hòa Trí",
    "Xã Tân Định",
    "Xã Nam Ninh Hòa",
    "Xã Khánh Vĩnh",
    "Xã Trung Khánh Vĩnh",
    "Xã Bắc Khánh Vĩnh",
    "Xã Tây Khánh Vĩnh",
    "Xã Nam Khánh Vĩnh",
    "Xã Diên Khánh",
    "Xã Diên Điền",
    "Xã Diên Lâm",
    "Xã Diên Thọ",
    "Xã Diên Lạc",
    "Xã Suối Hiệp",
    "Xã Suối Dầu",
    "Xã Khánh Sơn",
    "Xã Tây Khánh Sơn",
    "Xã Đông Khánh Sơn",
    "Xã Bác Ái Tây",
    "Xã Bác Ái",
    "Xã Bác Ái Đông",
    "Xã Ninh Sơn",
    "Xã Lâm Sơn",
    "Xã Mỹ Sơn",
    "Xã Anh Dũng",
    "Xã Công Hải",
    "Xã Vĩnh Hải",
    "Xã Thuận Bắc",
    "Xã Ninh Hải",
    "Xã Xuân Hải",
    "Xã Ninh Phước",
    "Xã Phước Hậu",
    "Xã Phước Dinh",
    "Xã Phước Hữu",
    "Xã Thuận Nam",
    "Xã Phước Hà",
    "Xã Cà Ná",
    "Đặc khu Trường Sa"
  ],
  "Tỉnh Đắk Lắk": [
    "Phường Tuy Hòa",
    "Phường Bình Kiến",
    "Phường Sông Cầu",
    "Phường Xuân Đài",
    "Phường Phú Yên",
    "Phường Đông Hòa",
    "Phường Hòa Hiệp",
    "Phường Tân Lập",
    "Phường Buôn Ma Thuột",
    "Phường Thành Nhất",
    "Phường Tân An",
    "Phường Ea Kao",
    "Phường Buôn Hồ",
    "Phường Cư Bao",
    "Xã Xuân Lộc",
    "Xã Xuân Cảnh",
    "Xã Xuân Thọ",
    "Xã Đồng Xuân",
    "Xã Xuân Lãnh",
    "Xã Phú Mỡ",
    "Xã Xuân Phước",
    "Xã Tuy An Bắc",
    "Xã Tuy An Đông",
    "Xã Tuy An Tây",
    "Xã Ô Loan",
    "Xã Tuy An Nam",
    "Xã Sơn Hòa",
    "Xã Tây Sơn",
    "Xã Vân Hòa",
    "Xã Suối Trai",
    "Xã Sông Hinh",
    "Xã Đức Bình",
    "Xã Ea Bá",
    "Xã Ea Ly",
    "Xã Sơn Thành",
    "Xã Tây Hòa",
    "Xã Hòa Thịnh",
    "Xã Hòa Mỹ",
    "Xã Hòa Xuân",
    "Xã Phú Hòa 2",
    "Xã Phú Hòa 1",
    "Xã Hòa Phú",
    "Xã Ea Drăng",
    "Xã Ea H'Leo",
    "Xã Ea Hiao",
    "Xã Ea Wy",
    "Xã Ea Khăl",
    "Xã Ea Súp",
    "Xã Ia Lốp",
    "Xã Ea Rốk",
    "Xã Ia Rvê",
    "Xã Ea Bung",
    "Xã Buôn Đôn",
    "Xã Ea Wer",
    "Xã Ea Nuôl",
    "Xã Quảng Phú",
    "Xã Ea Kiết",
    "Xã Ea Tul",
    "Xã Cư M'gar",
    "Xã Ea M'Droh",
    "Xã Cuôr Đăng",
    "Xã Krông Búk",
    "Xã Cư Pơng",
    "Xã Pơng Drang",
    "Xã Ea Drông",
    "Xã Krông Năng",
    "Xã Dliê Ya",
    "Xã Tam Giang",
    "Xã Phú Xuân",
    "Xã Ea Kar",
    "Xã Ea Knốp",
    "Xã Ea Păl",
    "Xã Ea Ô",
    "Xã Cư Yang",
    "Xã M'Drắk",
    "Xã Cư Prao",
    "Xã Ea Riêng",
    "Xã Cư M'ta",
    "Xã Krông Á",
    "Xã Ea Trang",
    "Xã Krông Bông",
    "Xã Dang Kang",
    "Xã Hòa Sơn",
    "Xã Cư Pui",
    "Xã Yang Mao",
    "Xã Krông Pắc",
    "Xã Ea Kly",
    "Xã Ea Phê",
    "Xã Ea Knuếc",
    "Xã Tân Tiến",
    "Xã Vụ Bổn",
    "Xã Krông Ana",
    "Xã Ea Ning",
    "Xã Ea Ktur",
    "Xã Ea Na",
    "Xã Dray Bhăng",
    "Xã Dur Kmăl",
    "Xã Liên Sơn Lắk",
    "Xã Đắk Liêng",
    "Xã Đắk Phơi",
    "Xã Krông Nô",
    "Xã Nam Ka"
  ],
  "Tỉnh Lâm Đồng": [
    "Phường Mũi Né",
    "Phường Phú Thủy",
    "Phường Hàm Thắng",
    "Phường Phan Thiết",
    "Phường Tiến Thành",
    "Phường Bình Thuận",
    "Phường Phước Hội",
    "Phường La Gi",
    "Phường Bắc Gia Nghĩa",
    "Phường Nam Gia Nghĩa",
    "Phường Đông Gia Nghĩa",
    "Phường Lâm Viên - Đà Lạt",
    "Phường Xuân Hương - Đà Lạt",
    "Phường Cam Ly - Đà Lạt",
    "Phường Xuân Trường - Đà Lạt",
    "Phường 2 Bảo Lộc",
    "Phường 1 Bảo Lộc",
    "Phường B'Lao",
    "Phường 3 Bảo Lộc",
    "Phường Lang Biang - Đà Lạt",
    "Xã Tuyên Quang",
    "Xã Liên Hương",
    "Xã Phan Rí Cửa",
    "Xã Tuy Phong",
    "Xã Vĩnh Hảo",
    "Xã Bắc Bình",
    "Xã Phan Sơn",
    "Xã Hải Ninh",
    "Xã Sông Lũy",
    "Xã Lương Sơn",
    "Xã Hồng Thái",
    "Xã Hòa Thắng",
    "Xã Hàm Thuận",
    "Xã La Dạ",
    "Xã Đông Giang",
    "Xã Hồng Sơn",
    "Xã Hàm Thuận Bắc",
    "Xã Hàm Liêm",
    "Xã Hàm Thuận Nam",
    "Xã Hàm Thạnh",
    "Xã Hàm Kiệm",
    "Xã Tân Lập",
    "Xã Tân Thành",
    "Xã Tánh Linh",
    "Xã Bắc Ruộng",
    "Xã Nghị Đức",
    "Xã Đồng Kho",
    "Xã Suối Kiết",
    "Xã Đức Linh",
    "Xã Hoài Đức",
    "Xã Nam Thành",
    "Xã Trà Tân",
    "Xã Tân Minh",
    "Xã Hàm Tân",
    "Xã Tân Hải",
    "Xã Sơn Mỹ",
    "Xã Quảng Sơn",
    "Xã Quảng Hòa",
    "Xã Quảng Khê",
    "Xã Tà Đùng",
    "Xã Cư Jút",
    "Xã Đắk Wil",
    "Xã Nam Dong",
    "Xã Đức Lập",
    "Xã Đắk Mil",
    "Xã Đắk Sắk",
    "Xã Thuận An",
    "Xã Krông Nô",
    "Xã Nam Đà",
    "Xã Nâm Nung",
    "Xã Quảng Phú",
    "Xã Đức An",
    "Xã Đắk Song",
    "Xã Thuận Hạnh",
    "Xã Trường Xuân",
    "Xã Kiến Đức",
    "Xã Quảng Trực",
    "Xã Tuy Đức",
    "Xã Quảng Tân",
    "Xã Nhân Cơ",
    "Xã Quảng Tín",
    "Xã Lạc Dương",
    "Xã Đam Rông 4",
    "Xã Nam Ban Lâm Hà",
    "Xã Đinh Văn Lâm Hà",
    "Xã Đam Rông 3",
    "Xã Đam Rông 2",
    "Xã Nam Hà Lâm Hà",
    "Xã Đam Rông 1",
    "Xã Phú Sơn Lâm Hà",
    "Xã Phúc Thọ Lâm Hà",
    "Xã Tân Hà Lâm Hà",
    "Xã Đơn Dương",
    "Xã D'Ran",
    "Xã Ka Đô",
    "Xã Quảng Lập",
    "Xã Đức Trọng",
    "Xã Hiệp Thạnh",
    "Xã Tân Hội",
    "Xã Ninh Gia",
    "Xã Tà Năng",
    "Xã Tà Hine",
    "Xã Di Linh",
    "Xã Đinh Trang Thượng",
    "Xã Gia Hiệp",
    "Xã Bảo Thuận",
    "Xã Hòa Ninh",
    "Xã Hòa Bắc",
    "Xã Sơn Điền",
    "Xã Bảo Lâm 1",
    "Xã Bảo Lâm 5",
    "Xã Bảo Lâm 4",
    "Xã Bảo Lâm 2",
    "Xã Bảo Lâm 3",
    "Xã Đạ Huoai",
    "Xã Đạ Huoai 2",
    "Xã Đạ Huoai 3",
    "Xã Đạ Tẻh",
    "Xã Đạ Tẻh 3",
    "Xã Đạ Tẻh 2",
    "Xã Cát Tiên",
    "Xã Cát Tiên 3",
    "Xã Cát Tiên 2",
    "Đặc khu Phú Quý"
  ],
  "Tỉnh Đồng Nai": [
    "Phường Bình Phước",
    "Phường Đồng Xoài",
    "Phường Phước Long",
    "Phường Phước Bình",
    "Phường Bình Long",
    "Phường An Lộc",
    "Phường Chơn Thành",
    "Phường Minh Hưng",
    "Phường Trảng Dài",
    "Phường Hố Nai",
    "Phường Tam Hiệp",
    "Phường Long Bình",
    "Phường Trấn Biên",
    "Phường Biên Hòa",
    "Phường Long Khánh",
    "Phường Bình Lộc",
    "Phường Bảo Vinh",
    "Phường Xuân Lập",
    "Phường Hàng Gòn",
    "Phường Tân Triều",
    "Phường Tam Phước",
    "Phường Phước Tân",
    "Phường Long Hưng",
    "Xã Bù Gia Mập",
    "Xã Đăk Ơ",
    "Xã Đa Kia",
    "Xã Bình Tân",
    "Xã Phú Riềng",
    "Xã Long Hà",
    "Xã Phú Trung",
    "Xã Phú Nghĩa",
    "Xã Lộc Ninh",
    "Xã Lộc Tấn",
    "Xã Lộc Thạnh",
    "Xã Lộc Quang",
    "Xã Lộc Thành",
    "Xã Lộc Hưng",
    "Xã Thiện Hưng",
    "Xã Hưng Phước",
    "Xã Tân Tiến",
    "Xã Tân Hưng",
    "Xã Minh Đức",
    "Xã Tân Quan",
    "Xã Tân Khai",
    "Xã Đồng Phú",
    "Xã Tân Lợi",
    "Xã Thuận Lợi",
    "Xã Đồng Tâm",
    "Xã Bù Đăng",
    "Xã Đak Nhau",
    "Xã Thọ Sơn",
    "Xã Bom Bo",
    "Xã Nghĩa Trung",
    "Xã Phước Sơn",
    "Xã Nha Bích",
    "Xã Tân Phú",
    "Xã Đak Lua",
    "Xã Nam Cát Tiên",
    "Xã Tà Lài",
    "Xã Phú Lâm",
    "Xã Trị An",
    "Xã Phú Lý",
    "Xã Tân An",
    "Xã Định Quán",
    "Xã Thanh Sơn",
    "Xã Phú Vinh",
    "Xã Phú Hòa",
    "Xã La Ngà",
    "Xã Trảng Bom",
    "Xã Bàu Hàm",
    "Xã Bình Minh",
    "Xã Hưng Thịnh",
    "Xã An Viễn",
    "Xã Thống Nhất",
    "Xã Gia Kiệm",
    "Xã Dầu Giây",
    "Xã Xuân Quế",
    "Xã Cẩm Mỹ",
    "Xã Xuân Đường",
    "Xã Xuân Đông",
    "Xã Sông Ray",
    "Xã Long Thành",
    "Xã An Phước",
    "Xã Bình An",
    "Xã Long Phước",
    "Xã Phước Thái",
    "Xã Xuân Lộc",
    "Xã Xuân Bắc",
    "Xã Xuân Thành",
    "Xã Xuân Hòa",
    "Xã Xuân Phú",
    "Xã Xuân Định",
    "Xã Nhơn Trạch",
    "Xã Đại Phước",
    "Xã Phước An"
  ],
  "Thành phố Hồ Chí Minh": [
    "Phường Thủ Dầu Một",
    "Phường Phú Lợi",
    "Phường Bình Dương",
    "Phường Phú An",
    "Phường Chánh Hiệp",
    "Phường Bến Cát",
    "Phường Chánh Phú Hòa",
    "Phường Long Nguyên",
    "Phường Tây Nam",
    "Phường Thới Hòa",
    "Phường Hòa Lợi",
    "Phường Tân Uyên",
    "Phường Tân Khánh",
    "Phường Vĩnh Tân",
    "Phường Bình Cơ",
    "Phường Tân Hiệp",
    "Phường Dĩ An",
    "Phường Tân Đông Hiệp",
    "Phường Đông Hòa",
    "Phường Lái Thiêu",
    "Phường Thuận Giao",
    "Phường An Phú",
    "Phường Thuận An",
    "Phường Bình Hòa",
    "Phường Vũng Tàu",
    "Phường Tam Thắng",
    "Phường Rạch Dừa",
    "Phường Phước Thắng",
    "Phường Bà Rịa",
    "Phường Long Hương",
    "Phường Tam Long",
    "Phường Phú Mỹ",
    "Phường Tân Hải",
    "Phường Tân Phước",
    "Phường Tân Thành",
    "Phường Tân Định",
    "Phường Sài Gòn",
    "Phường Bến Thành",
    "Phường Cầu Ông Lãnh",
    "Phường An Phú Đông",
    "Phường Thới An",
    "Phường Tân Thới Hiệp",
    "Phường Trung Mỹ Tây",
    "Phường Đông Hưng Thuận",
    "Phường Linh Xuân",
    "Phường Tam Bình",
    "Phường Hiệp Bình",
    "Phường Thủ Đức",
    "Phường Long Bình",
    "Phường Tăng Nhơn Phú",
    "Phường Phước Long",
    "Phường Long Phước",
    "Phường Long Trường",
    "Phường An Nhơn",
    "Phường An Hội Đông",
    "Phường An Hội Tây",
    "Phường Gò Vấp",
    "Phường Hạnh Thông",
    "Phường Thông Tây Hội",
    "Phường Bình Lợi Trung",
    "Phường Bình Quới",
    "Phường Bình Thạnh",
    "Phường Gia Định",
    "Phường Thạnh Mỹ Tây",
    "Phường Tân Sơn Nhất",
    "Phường Tân Sơn Hòa",
    "Phường Bảy Hiền",
    "Phường Tân Hòa",
    "Phường Tân Bình",
    "Phường Tân Sơn",
    "Phường Tây Thạnh",
    "Phường Tân Sơn Nhì",
    "Phường Phú Thọ Hòa",
    "Phường Phú Thạnh",
    "Phường Tân Phú",
    "Phường Đức Nhuận",
    "Phường Cầu Kiệu",
    "Phường Phú Nhuận",
    "Phường An Khánh",
    "Phường Bình Trưng",
    "Phường Cát Lái",
    "Phường Xuân Hòa",
    "Phường Nhiêu Lộc",
    "Phường Bàn Cờ",
    "Phường Hòa Hưng",
    "Phường Diên Hồng",
    "Phường Vườn Lài",
    "Phường Hòa Bình",
    "Phường Phú Thọ",
    "Phường Bình Thới",
    "Phường Minh Phụng",
    "Phường Xóm Chiếu",
    "Phường Khánh Hội",
    "Phường Vĩnh Hội",
    "Phường Chợ Quán",
    "Phường An Đông",
    "Phường Chợ Lớn",
    "Phường Phú Lâm",
    "Phường Bình Phú",
    "Phường Bình Tây",
    "Phường Bình Tiên",
    "Phường Chánh Hưng",
    "Phường Bình Đông",
    "Phường Phú Định",
    "Phường Bình Hưng Hòa",
    "Phường Bình Tân",
    "Phường Bình Trị Đông",
    "Phường Tân Tạo",
    "Phường An Lạc",
    "Phường Tân Hưng",
    "Phường Tân Thuận",
    "Phường Phú Thuận",
    "Phường Tân Mỹ",
    "Xã Dầu Tiếng",
    "Xã Minh Thạnh",
    "Xã Long Hòa",
    "Xã Thanh An",
    "Xã Trừ Văn Thố",
    "Xã Bàu Bàng",
    "Xã Phú Giáo",
    "Xã Phước Thành",
    "Xã An Long",
    "Xã Phước Hòa",
    "Xã Bắc Tân Uyên",
    "Xã Thường Tân",
    "Xã Long Sơn",
    "Xã Ngãi Giao",
    "Xã Xuân Sơn",
    "Xã Bình Giã",
    "Xã Châu Đức",
    "Xã Kim Long",
    "Xã Nghĩa Thành",
    "Xã Hồ Tràm",
    "Xã Xuyên Mộc",
    "Xã Bàu Lâm",
    "Xã Hòa Hội",
    "Xã Hòa Hiệp",
    "Xã Bình Châu",
    "Xã Long Điền",
    "Xã Long Hải",
    "Xã Đất Đỏ",
    "Xã Phước Hải",
    "Xã Châu Pha",
    "Xã Tân An Hội",
    "Xã An Nhơn Tây",
    "Xã Nhuận Đức",
    "Xã Thái Mỹ",
    "Xã Phú Hòa Đông",
    "Xã Bình Mỹ",
    "Xã Củ Chi",
    "Xã Hóc Môn",
    "Xã Đông Thạnh",
    "Xã Xuân Thới Sơn",
    "Xã Bà Điểm",
    "Xã Tân Nhựt",
    "Xã Vĩnh Lộc",
    "Xã Tân Vĩnh Lộc",
    "Xã Bình Lợi",
    "Xã Bình Hưng",
    "Xã Hưng Long",
    "Xã Bình Chánh",
    "Xã Nhà Bè",
    "Xã Hiệp Phước",
    "Xã Cần Giờ",
    "Xã Bình Khánh",
    "Xã An Thới Đông",
    "Xã Thạnh An",
    "Đặc khu Côn Đảo"
  ],
  "Tỉnh Tây Ninh": [
    "Phường Tân Ninh",
    "Phường Bình Minh",
    "Phường Ninh Thạnh",
    "Phường Long Hoa",
    "Phường Thanh Điền",
    "Phường Hòa Thành",
    "Phường Gò Dầu",
    "Phường Gia Lộc",
    "Phường Trảng Bàng",
    "Phường An Tịnh",
    "Phường Long An",
    "Phường Tân An",
    "Phường Khánh Hậu",
    "Phường Kiến Tường",
    "Xã Tân Biên",
    "Xã Tân Lập",
    "Xã Thạnh Bình",
    "Xã Trà Vong",
    "Xã Tân Châu",
    "Xã Tân Đông",
    "Xã Tân Hội",
    "Xã Tân Hòa",
    "Xã Tân Thành",
    "Xã Tân Phú",
    "Xã Dương Minh Châu",
    "Xã Cầu Khởi",
    "Xã Lộc Ninh",
    "Xã Châu Thành",
    "Xã Hảo Đước",
    "Xã Phước Vinh",
    "Xã Hòa Hội",
    "Xã Ninh Điền",
    "Xã Thạnh Đức",
    "Xã Phước Thạnh",
    "Xã Truông Mít",
    "Xã Bến Cầu",
    "Xã Long Chữ",
    "Xã Long Thuận",
    "Xã Hưng Thuận",
    "Xã Phước Chỉ",
    "Xã Tân Hưng",
    "Xã Hưng Điền",
    "Xã Vĩnh Thạnh",
    "Xã Vĩnh Châu",
    "Xã Vĩnh Hưng",
    "Xã Khánh Hưng",
    "Xã Tuyên Bình",
    "Xã Bình Hiệp",
    "Xã Bình Hòa",
    "Xã Tuyên Thạnh",
    "Xã Mộc Hóa",
    "Xã Tân Thạnh",
    "Xã Nhơn Hòa Lập",
    "Xã Hậu Thạnh",
    "Xã Nhơn Ninh",
    "Xã Thạnh Hóa",
    "Xã Bình Thành",
    "Xã Thạnh Phước",
    "Xã Tân Tây",
    "Xã Đông Thành",
    "Xã Mỹ Quý",
    "Xã Đức Huệ",
    "Xã Hậu Nghĩa",
    "Xã Đức Hòa",
    "Xã An Ninh",
    "Xã Hiệp Hòa",
    "Xã Đức Lập",
    "Xã Mỹ Hạnh",
    "Xã Hòa Khánh",
    "Xã Bến Lức",
    "Xã Thạnh Lợi",
    "Xã Lương Hòa",
    "Xã Bình Đức",
    "Xã Mỹ Yên",
    "Xã Thủ Thừa",
    "Xã Mỹ Thạnh",
    "Xã Mỹ An",
    "Xã Tân Long",
    "Xã Tân Trụ",
    "Xã Nhựt Tảo",
    "Xã Vàm Cỏ",
    "Xã Cần Đước",
    "Xã Rạch Kiến",
    "Xã Long Cang",
    "Xã Mỹ Lệ",
    "Xã Tân Lân",
    "Xã Long Hựu",
    "Xã Cần Giuộc",
    "Xã Phước Lý",
    "Xã Mỹ Lộc",
    "Xã Phước Vĩnh Tây",
    "Xã Tân Tập",
    "Xã Tầm Vu",
    "Xã Vĩnh Công",
    "Xã Thuận Mỹ",
    "Xã An Lục Long"
  ],
  "Tỉnh Đồng Tháp": [
    "Xã An Phước",
    "Phường Đạo Thạnh",
    "Phường Mỹ Tho",
    "Phường Thới Sơn",
    "Phường Mỹ Phong",
    "Phường Trung An",
    "Phường Long Thuận",
    "Phường Gò Công",
    "Phường Bình Xuân",
    "Phường Mỹ Phước Tây",
    "Phường Thanh Hòa",
    "Phường Cai Lậy",
    "Phường Nhị Quý",
    "Phường Sơn Qui",
    "Phường Cao Lãnh",
    "Phường Mỹ Ngãi",
    "Phường Mỹ Trà",
    "Phường Sa Đéc",
    "Phường An Bình",
    "Phường Hồng Ngự",
    "Phường Thường Lạc",
    "Xã Tân Phước 1",
    "Xã Tân Phước 2",
    "Xã Hưng Thạnh",
    "Xã Tân Phước 3",
    "Xã Cái Bè",
    "Xã Hậu Mỹ",
    "Xã Mỹ Thiện",
    "Xã Hội Cư",
    "Xã Mỹ Đức Tây",
    "Xã Mỹ Lợi",
    "Xã Thanh Hưng",
    "Xã An Hữu",
    "Xã Thạnh Phú",
    "Xã Mỹ Thành",
    "Xã Tân Phú",
    "Xã Bình Phú",
    "Xã Hiệp Đức",
    "Xã Long Tiên",
    "Xã Ngũ Hiệp",
    "Xã Châu Thành",
    "Xã Tân Hương",
    "Xã Long Hưng",
    "Xã Long Định",
    "Xã Bình Trưng",
    "Xã Vĩnh Kim",
    "Xã Kim Sơn",
    "Xã Chợ Gạo",
    "Xã Mỹ Tịnh An",
    "Xã Lương Hòa Lạc",
    "Xã Tân Thuận Bình",
    "Xã An Thạnh Thủy",
    "Xã Bình Ninh",
    "Xã Vĩnh Bình",
    "Xã Đồng Sơn",
    "Xã Phú Thành",
    "Xã Vĩnh Hựu",
    "Xã Long Bình",
    "Xã Tân Thới",
    "Xã Tân Phú Đông",
    "Xã Tân Hòa",
    "Xã Gia Thuận",
    "Xã Tân Đông",
    "Xã Tân Điền",
    "Xã Gò Công Đông",
    "Xã Tân Hồng",
    "Xã Tân Hộ Cơ",
    "Xã Tân Thành",
    "Xã Thường Phước",
    "Xã Long Khánh",
    "Xã Long Phú Thuận",
    "Xã Tràm Chim",
    "Xã Tam Nông",
    "Xã An Hòa",
    "Xã Phú Cường",
    "Xã An Long",
    "Xã Phú Thọ",
    "Xã Tháp Mười",
    "Xã Phương Thịnh",
    "Xã Trường Xuân",
    "Xã Mỹ Quí",
    "Xã Đốc Binh Kiều",
    "Xã Thanh Mỹ",
    "Xã Mỹ Thọ",
    "Xã Ba Sao",
    "Xã Phong Mỹ",
    "Xã Mỹ Hiệp",
    "Xã Bình Hàng Trung",
    "Xã Thanh Bình",
    "Xã Tân Long",
    "Xã Tân Thạnh",
    "Xã Bình Thành",
    "Xã Lấp Vò",
    "Xã Mỹ An Hưng",
    "Xã Tân Khánh Trung",
    "Xã Hòa Long",
    "Xã Tân Dương",
    "Xã Lai Vung",
    "Xã Phong Hòa",
    "Xã Phú Hựu",
    "Xã Tân Nhuận Đông",
    "Xã Tân Phú Trung"
  ],
  "Tỉnh Vĩnh Long": [
    "Phường Phú Khương",
    "Phường An Hội",
    "Phường Sơn Đông",
    "Phường Bến Tre",
    "Phường Phú Tân",
    "Phường Trà Vinh",
    "Phường Nguyệt Hóa",
    "Phường Long Đức",
    "Phường Hòa Thuận",
    "Phường Duyên Hải",
    "Phường Trường Long Hòa",
    "Phường Long Châu",
    "Phường Phước Hậu",
    "Phường Tân Ngãi",
    "Phường Thanh Đức",
    "Phường Tân Hạnh",
    "Phường Cái Vồn",
    "Phường Bình Minh",
    "Phường Đông Thành",
    "Xã Giao Long",
    "Xã Phú Túc",
    "Xã Tân Phú",
    "Xã Tiên Thủy",
    "Xã Chợ Lách",
    "Xã Phú Phụng",
    "Xã Vĩnh Thành",
    "Xã Hưng Khánh Trung",
    "Xã Mỏ Cày",
    "Xã Phước Mỹ Trung",
    "Xã Tân Thành Bình",
    "Xã Đồng Khởi",
    "Xã Nhuận Phú Tân",
    "Xã An Định",
    "Xã Thành Thới",
    "Xã Hương Mỹ",
    "Xã Giồng Trôm",
    "Xã Lương Hòa",
    "Xã Lương Phú",
    "Xã Châu Hòa",
    "Xã Phước Long",
    "Xã Tân Hào",
    "Xã Hưng Nhượng",
    "Xã Bình Đại",
    "Xã Phú Thuận",
    "Xã Lộc Thuận",
    "Xã Châu Hưng",
    "Xã Thạnh Trị",
    "Xã Thạnh Phước",
    "Xã Thới Thuận",
    "Xã Ba Tri",
    "Xã Mỹ Chánh Hòa",
    "Xã Bảo Thạnh",
    "Xã Tân Xuân",
    "Xã An Ngãi Trung",
    "Xã An Hiệp",
    "Xã Tân Thủy",
    "Xã Thạnh Phú",
    "Xã Quới Điền",
    "Xã Đại Điền",
    "Xã Thạnh Hải",
    "Xã An Qui",
    "Xã Thạnh Phong",
    "Xã Càng Long",
    "Xã An Trường",
    "Xã Tân An",
    "Xã Bình Phú",
    "Xã Nhị Long",
    "Xã Cầu Kè",
    "Xã An Phú Tân",
    "Xã Phong Thạnh",
    "Xã Tam Ngãi",
    "Xã Tiểu Cần",
    "Xã Hùng Hòa",
    "Xã Tập Ngãi",
    "Xã Tân Hòa",
    "Xã Châu Thành",
    "Xã Song Lộc",
    "Xã Hưng Mỹ",
    "Xã Hòa Minh",
    "Xã Long Hòa",
    "Xã Cầu Ngang",
    "Xã Mỹ Long",
    "Xã Vinh Kim",
    "Xã Nhị Trường",
    "Xã Hiệp Mỹ",
    "Xã Trà Cú",
    "Xã Tập Sơn",
    "Xã Lưu Nghiệp Anh",
    "Xã Hàm Giang",
    "Xã Đại An",
    "Xã Đôn Châu",
    "Xã Long Hiệp",
    "Xã Long Thành",
    "Xã Long Hữu",
    "Xã Ngũ Lạc",
    "Xã Long Vĩnh",
    "Xã Đông Hải",
    "Xã An Bình",
    "Xã Long Hồ",
    "Xã Phú Quới",
    "Xã Nhơn Phú",
    "Xã Bình Phước",
    "Xã Cái Nhum",
    "Xã Tân Long Hội",
    "Xã Trung Thành",
    "Xã Quới An",
    "Xã Quới Thiện",
    "Xã Trung Hiệp",
    "Xã Trung Ngãi",
    "Xã Hiếu Phụng",
    "Xã Hiếu Thành",
    "Xã Tam Bình",
    "Xã Cái Ngang",
    "Xã Hòa Hiệp",
    "Xã Song Phú",
    "Xã Ngãi Tứ",
    "Xã Tân Lược",
    "Xã Mỹ Thuận",
    "Xã Tân Quới",
    "Xã Trà Ôn",
    "Xã Hòa Bình",
    "Xã Trà Côn",
    "Xã Vĩnh Xuân",
    "Xã Lục Sĩ Thành"
  ],
  "Tỉnh An Giang": [
    "Phường Bình Đức",
    "Phường Mỹ Thới",
    "Phường Long Xuyên",
    "Phường Châu Đốc",
    "Phường Vĩnh Tế",
    "Phường Tân Châu",
    "Phường Long Phú",
    "Phường Thới Sơn",
    "Phường Chi Lăng",
    "Phường Tịnh Biên",
    "Phường Rạch Giá",
    "Phường Vĩnh Thông",
    "Phường Tô Châu",
    "Phường Hà Tiên",
    "Xã Mỹ Hòa Hưng",
    "Xã An Phú",
    "Xã Khánh Bình",
    "Xã Nhơn Hội",
    "Xã Phú Hữu",
    "Xã Vĩnh Hậu",
    "Xã Vĩnh Xương",
    "Xã Tân An",
    "Xã Châu Phong",
    "Xã Phú Tân",
    "Xã Chợ Vàm",
    "Xã Phú Lâm",
    "Xã Hòa Lạc",
    "Xã Phú An",
    "Xã Bình Thạnh Đông",
    "Xã Châu Phú",
    "Xã Mỹ Đức",
    "Xã Vĩnh Thạnh Trung",
    "Xã Thạnh Mỹ Tây",
    "Xã Bình Mỹ",
    "Xã An Cư",
    "Xã Núi Cấm",
    "Xã Tri Tôn",
    "Xã Ba Chúc",
    "Xã Vĩnh Gia",
    "Xã Ô Lâm",
    "Xã Cô Tô",
    "Xã An Châu",
    "Xã Cần Đăng",
    "Xã Vĩnh An",
    "Xã Bình Hòa",
    "Xã Vĩnh Hanh",
    "Xã Chợ Mới",
    "Xã Long Điền",
    "Xã Cù Lao Giêng",
    "Xã Nhơn Mỹ",
    "Xã Long Kiến",
    "Xã Hội An",
    "Xã Thoại Sơn",
    "Xã Phú Hòa",
    "Xã Óc Eo",
    "Xã Tây Phú",
    "Xã Vĩnh Trạch",
    "Xã Định Mỹ",
    "Xã Tiên Hải",
    "Xã Kiên Lương",
    "Xã Hòa Điền",
    "Xã Vĩnh Điều",
    "Xã Giang Thành",
    "Xã Sơn Hải",
    "Xã Hòn Nghệ",
    "Xã Hòn Đất",
    "Xã Bình Sơn",
    "Xã Bình Giang",
    "Xã Sơn Kiên",
    "Xã Mỹ Thuận",
    "Xã Tân Hiệp",
    "Xã Tân Hội",
    "Xã Thạnh Đông",
    "Xã Châu Thành",
    "Xã Thạnh Lộc",
    "Xã Bình An",
    "Xã Giồng Riềng",
    "Xã Thạnh Hưng",
    "Xã Ngọc Chúc",
    "Xã Hòa Hưng",
    "Xã Long Thạnh",
    "Xã Hòa Thuận",
    "Xã Gò Quao",
    "Xã Định Hòa",
    "Xã Vĩnh Hòa Hưng",
    "Xã Vĩnh Tuy",
    "Xã An Biên",
    "Xã Tây Yên",
    "Xã Đông Thái",
    "Xã Vĩnh Hòa",
    "Xã An Minh",
    "Xã Đông Hòa",
    "Xã U Minh Thượng",
    "Xã Tân Thạnh",
    "Xã Đông Hưng",
    "Xã Vân Khánh",
    "Xã Vĩnh Phong",
    "Xã Vĩnh Bình",
    "Xã Vĩnh Thuận",
    "Đặc khu Phú Quốc",
    "Đặc khu Thổ Châu",
    "Đặc khu Kiên Hải"
  ],
  "Thành phố Cần Thơ": [
    "Phường Cái Khế",
    "Phường Ninh Kiều",
    "Phường Tân An",
    "Phường An Bình",
    "Phường Ô Môn",
    "Phường Thới Long",
    "Phường Phước Thới",
    "Phường Bình Thủy",
    "Phường Thới An Đông",
    "Phường Long Tuyền",
    "Phường Cái Răng",
    "Phường Hưng Phú",
    "Phường Thốt Nốt",
    "Phường Tân Lộc",
    "Phường Trung Nhứt",
    "Phường Thuận Hưng",
    "Phường Vị Thanh",
    "Phường Vị Tân",
    "Phường Ngã Bảy",
    "Phường Đại Thành",
    "Phường Long Mỹ",
    "Phường Long Bình",
    "Phường Long Phú 1",
    "Phường Sóc Trăng",
    "Phường Phú Lợi",
    "Phường Mỹ Xuyên",
    "Phường Ngã Năm",
    "Phường Mỹ Quới",
    "Phường Vĩnh Châu",
    "Phường Khánh Hòa",
    "Phường Vĩnh Phước",
    "Xã Thạnh An",
    "Xã Vĩnh Thạnh",
    "Xã Vĩnh Trinh",
    "Xã Thạnh Quới",
    "Xã Thạnh Phú",
    "Xã Trung Hưng",
    "Xã Thới Lai",
    "Xã Cờ Đỏ",
    "Xã Thới Hưng",
    "Xã Đông Hiệp",
    "Xã Đông Thuận",
    "Xã Trường Thành",
    "Xã Trường Xuân",
    "Xã Phong Điền",
    "Xã Trường Long",
    "Xã Nhơn Ái",
    "Xã Hỏa Lựu",
    "Xã Tân Hòa",
    "Xã Trường Long Tây",
    "Xã Thạnh Xuân",
    "Xã Châu Thành",
    "Xã Đông Phước",
    "Xã Phú Hữu",
    "Xã Hòa An",
    "Xã Hiệp Hưng",
    "Xã Tân Bình",
    "Xã Thạnh Hòa",
    "Xã Phụng Hiệp",
    "Xã Phương Bình",
    "Xã Tân Phước Hưng",
    "Xã Vị Thủy",
    "Xã Vĩnh Thuận Đông",
    "Xã Vĩnh Tường",
    "Xã Vị Thanh 1",
    "Xã Vĩnh Viễn",
    "Xã Lương Tâm",
    "Xã Xà Phiên",
    "Xã Kế Sách",
    "Xã An Lạc Thôn",
    "Xã Phong Nẫm",
    "Xã Thới An Hội",
    "Xã Nhơn Mỹ",
    "Xã Đại Hải",
    "Xã Mỹ Tú",
    "Xã Phú Tâm",
    "Xã Hồ Đắc Kiện",
    "Xã Long Hưng",
    "Xã Thuận Hòa",
    "Xã Mỹ Hương",
    "Xã An Ninh",
    "Xã Mỹ Phước",
    "Xã An Thạnh",
    "Xã Cù Lao Dung",
    "Xã Long Phú",
    "Xã Đại Ngãi",
    "Xã Trường Khánh",
    "Xã Tân Thạnh",
    "Xã Trần Đề",
    "Xã Liêu Tú",
    "Xã Lịch Hội Thượng",
    "Xã Tài Văn",
    "Xã Thạnh Thới An",
    "Xã Nhu Gia",
    "Xã Hòa Tú",
    "Xã Ngọc Tố",
    "Xã Gia Hòa",
    "Xã Tân Long",
    "Xã Phú Lộc",
    "Xã Lâm Tân",
    "Xã Vĩnh Lợi",
    "Xã Vĩnh Hải",
    "Xã Lai Hòa"
  ],
  "Tỉnh Cà Mau": [
    "Phường Bạc Liêu",
    "Phường Vĩnh Trạch",
    "Phường Hiệp Thành",
    "Phường Giá Rai",
    "Phường Láng Tròn",
    "Phường An Xuyên",
    "Phường Lý Văn Lâm",
    "Phường Tân Thành",
    "Phường Hòa Thành",
    "Xã Hồng Dân",
    "Xã Ninh Quới",
    "Xã Vĩnh Lộc",
    "Xã Ninh Thạnh Lợi",
    "Xã Phước Long",
    "Xã Vĩnh Phước",
    "Xã Vĩnh Thanh",
    "Xã Phong Hiệp",
    "Xã Hòa Bình",
    "Xã Châu Thới",
    "Xã Vĩnh Lợi",
    "Xã Hưng Hội",
    "Xã Vĩnh Mỹ",
    "Xã Vĩnh Hậu",
    "Xã Phong Thạnh",
    "Xã Gành Hào",
    "Xã Đông Hải",
    "Xã Long Điền",
    "Xã An Trạch",
    "Xã Định Thành",
    "Xã Nguyễn Phích",
    "Xã U Minh",
    "Xã Khánh An",
    "Xã Khánh Lâm",
    "Xã Thới Bình",
    "Xã Biển Bạch",
    "Xã Trí Phải",
    "Xã Tân Lộc",
    "Xã Hồ Thị Kỷ",
    "Xã Trần Văn Thời",
    "Xã Sông Đốc",
    "Xã Đá Bạc",
    "Xã Khánh Bình",
    "Xã Khánh Hưng",
    "Xã Cái Nước",
    "Xã Lương Thế Trân",
    "Xã Tân Hưng",
    "Xã Hưng Mỹ",
    "Xã Đầm Dơi",
    "Xã Tạ An Khương",
    "Xã Trần Phán",
    "Xã Tân Thuận",
    "Xã Quách Phẩm",
    "Xã Thanh Tùng",
    "Xã Tân Tiến",
    "Xã Năm Căn",
    "Xã Đất Mới",
    "Xã Tam Giang",
    "Xã Cái Đôi Vàm",
    "Xã Phú Mỹ",
    "Xã Phú Tân",
    "Xã Nguyễn Việt Khái",
    "Xã Tân Ân",
    "Xã Phan Ngọc Hiển",
    "Xã Đất Mũi"
  ]
};

export const getDistrictsOrWards = (province: string) => {
  return (DISTRICT_WARD_MAP[province] || []).map((d) => ({ label: d, value: d }));
};

