import type { WeeklyReportData } from '../../services/weekly-report.service';

export const sampleMonthlyReport: WeeklyReportData = {
  id: 'rep-stu-1040-oct2026',
  studentId: 'STU-1040',
  studentName: 'Nguyễn Khánh Phương',
  studentCode: 'STU-1040',
  weekNumber: 10,
  year: 2026,
  startDate: '2026-10-01',
  endDate: '2026-10-31',
  sqiScore: 75,
  sqiDelta: -11.2,
  sqiBreakdown: {
    attendance: 22.5,
    homework: 20,
    behavior: 16,
    participation: 16.5,
    narratives: {
      attendance: '1 buổi đi muộn',
      homework: 'Làm tốt các buổi có bài tập',
      behavior: 'Nề nếp tốt, nghiêm túc',
      participation: 'Chủ động phát biểu trong lớp',
    },
  },
  subjectPerformances: [
    { subjectName: 'Toán học', score: 8.5, trend: 'up' },
  ],
  overview: 'Học sinh tham gia học tập nghiêm túc, cần khắc phục việc đi muộn và tiếp tục phát huy ưu điểm.',
  commendation: 'Tuyên dương tinh thần chủ động phát biểu xây dựng bài trong các buổi học.',
  suggestion: 'Động viên con tiếp tục phát huy tinh thần tự giác trong các buổi học tiếp theo.',
  strengths: 'Tham gia học tập đầy đủ, đúng giờ trong phần lớn các buổi. Tiếp thu bài nhanh.',
  improvements: 'Duy trì phong độ tốt, không có vi phạm nề nếp. Cần đi học đúng giờ.',
  recommendations: [
    'Dành 20 phút mỗi tối ôn lại dạng toán đại số.',
    'Chủ động chuẩn bị bài trước khi đến lớp.',
  ],
  isApproved: true,
  approvedBy: 'ThS. Hoàng Đức Minh',
  approvedAt: '2026-10-02T10:00:00Z',
  sessions: [
    {
      classSessionId: 'sess-01',
      className: 'LỚP CỦNG CỐ KIẾN THỨC THCS - TOÁN 8',
      subjectName: 'Toán 8',
      date: '2026-10-01',
      isPresent: true,
      isLate: false,
      attendanceStatus: 'present',
      homeworkStatus: 'completed',
      participation: 'active',
      behaviorStatus: 'good',
      score: '8.5',
      teacherComment: 'Tiếp thu bài nhanh, làm bài tập đầy đủ.',
    },
    {
      classSessionId: 'sess-02',
      className: 'LỚP CỦNG CỐ KIẾN THỨC THCS - TOÁN 8',
      subjectName: 'Toán 8',
      date: '2026-10-08',
      isPresent: true,
      isLate: true,
      attendanceStatus: 'late',
      homeworkStatus: 'completed',
      participation: 'medium',
      behaviorStatus: 'good',
      score: '8.0',
      teacherComment: 'Đi muộn 10 phút, trong giờ chăm chú lắng nghe.',
    },
    {
      classSessionId: 'sess-03',
      className: 'LỚP CỦNG CỐ KIẾN THỨC THCS - TOÁN 8',
      subjectName: 'Toán 8',
      date: '2026-10-15',
      isPresent: true,
      isLate: false,
      attendanceStatus: 'present',
      homeworkStatus: 'completed',
      participation: 'active',
      behaviorStatus: 'good',
      score: '9.0',
      teacherComment: 'Hăng hái xung phong lên bảng giải bài.',
    },
    {
      classSessionId: 'sess-04',
      className: 'LỚP CỦNG CỐ KIẾN THỨC THCS - TOÁN 8',
      subjectName: 'Toán 8',
      date: '2026-10-22',
      isPresent: true,
      isLate: false,
      attendanceStatus: 'present',
      homeworkStatus: 'completed',
      participation: 'active',
      behaviorStatus: 'good',
      score: '8.5',
      teacherComment: 'Hoàn thành bài kiểm tra cuối chuyên đề tốt.',
    },
  ],
};
